export type StructurePattern = {
  id: string;
  intent: string;
  template: string;
};

export const structures: StructurePattern[] = [
  { id: "warm-direct", intent: "greeting", template: "{response}" },
  { id: "identity-direct", intent: "identity", template: "{response}" },
  { id: "origin-direct", intent: "origin", template: "{response}" },
  { id: "mechanism-sequence", intent: "mechanism", template: "{response}" },
  { id: "contrast-direct", intent: "compare-ai", template: "{response}" },
  { id: "module-explanation", intent: "context-module", template: "{response}" },
  { id: "module-explanation", intent: "search-module", template: "{response}" },
  { id: "module-explanation", intent: "connect-module", template: "{response}" },
  { id: "module-explanation", intent: "structure-module", template: "{response}" },
  { id: "capability-bounded", intent: "capabilities", template: "{response}" },
  { id: "limitation-cautious", intent: "limitations", template: "{response}" },
  { id: "gratitude-brief", intent: "gratitude", template: "{response}" },
  { id: "farewell-brief", intent: "farewell", template: "{response}" },
  { id: "wellbeing-mechanical", intent: "wellbeing", template: "{response}" },
  { id: "help-menu", intent: "help", template: "{response}" },
  { id: "introduction-warm", intent: "introduction", template: "{response}" },
  { id: "name-direct", intent: "ask-name", template: "{response}" },
  { id: "apology-acknowledgement", intent: "apology", template: "{response}" },
  { id: "apology-accepted", intent: "accept-apology", template: "{response}" },
  { id: "acknowledgement-brief", intent: "acknowledgement", template: "{response}" },
  { id: "agreement-brief", intent: "agreement", template: "{response}" },
  { id: "disagreement-respectful", intent: "disagreement", template: "{response}" },
  { id: "clarification-prompt", intent: "clarification-request", template: "{response}" },
  { id: "repetition-prompt", intent: "repetition-request", template: "{response}" },
  { id: "confirmation-bounded", intent: "confirmation-question", template: "{response}" },
  { id: "request-bounded", intent: "simple-request", template: "{response}" },
  { id: "permission-direct", intent: "permission-request", template: "{response}" },
  { id: "offer-acknowledgement", intent: "offer-help", template: "{response}" },
  { id: "invitation-text-only", intent: "invitation", template: "{response}" },
  { id: "invitation-accepted", intent: "accept-invitation", template: "{response}" },
  { id: "invitation-declined", intent: "decline-invitation", template: "{response}" },
  { id: "preference-bounded", intent: "preference-question", template: "{response}" },
  { id: "like-acknowledgement", intent: "express-like", template: "{response}" },
  { id: "dislike-acknowledgement", intent: "express-dislike", template: "{response}" },
  { id: "positive-feeling-acknowledgement", intent: "positive-feeling", template: "{response}" },
  { id: "negative-feeling-acknowledgement", intent: "negative-feeling", template: "{response}" },
  { id: "compliment-thanks", intent: "compliment", template: "{response}" },
  { id: "congratulations-thanks", intent: "congratulations", template: "{response}" },
  { id: "encouragement-thanks", intent: "encouragement", template: "{response}" },
  { id: "small-talk-bounded", intent: "small-talk", template: "{response}" },
  { id: "time-live-source", intent: "ask-time", template: "{response}" },
  { id: "time-acknowledgement", intent: "state-time", template: "{response}" },
  { id: "date-live-source", intent: "ask-date", template: "{response}" },
  { id: "date-acknowledgement", intent: "state-date", template: "{response}" },
  { id: "morning-routine-acknowledgement", intent: "morning-routine", template: "{response}" },
  { id: "evening-routine-acknowledgement", intent: "evening-routine", template: "{response}" },
  { id: "meal-constraints", intent: "meal-planning", template: "{response}" },
  { id: "food-order-recognition", intent: "food-order", template: "{response}" },
  { id: "drink-request-recognition", intent: "drink-request", template: "{response}" },
  { id: "study-activity-acknowledgement", intent: "study-activity", template: "{response}" },
  { id: "classroom-material-request", intent: "classroom-help", template: "{response}" },
  { id: "work-update-acknowledgement", intent: "work-update", template: "{response}" },
  { id: "task-constraints", intent: "task-planning", template: "{response}" },
  { id: "schedule-live-source", intent: "scheduling-request", template: "{response}" },
  { id: "inventory-live-source", intent: "product-availability", template: "{response}" },
  { id: "price-live-source", intent: "price-question", template: "{response}" },
  { id: "quantity-recognition", intent: "quantity-request", template: "{response}" },
  { id: "travel-constraints", intent: "travel-planning", template: "{response}" },
  { id: "transport-live-source", intent: "transport-question", template: "{response}" },
  { id: "directions-map-source", intent: "direction-request", template: "{response}" },
  { id: "location-context", intent: "location-question", template: "{response}" },
  { id: "weather-live-source", intent: "weather-question", template: "{response}" },
  { id: "clothing-constraints", intent: "clothing-consideration", template: "{response}" },
  { id: "chore-acknowledgement", intent: "household-chore", template: "{response}" },
  { id: "sleep-routine-acknowledgement", intent: "sleep-routine", template: "{response}" },
  {
    id: "synonym-list",
    intent: "synonym",
    template: "In the current lexicon, {subject} {action} {object}{qualifier}.",
  },
  {
    id: "definition-direct",
    intent: "definition",
    template: "{subject} {action} {object}{qualifier}.",
  },
  {
    id: "unknown-safe",
    intent: "unknown",
    template:
      "I cannot connect that wording to a sufficiently close recorded context yet. Try asking about Lexi, Alphaine, the modules, sentence structure, or a synonym.",
  },
];
