import type { ConversationRule, PackResponse } from "./types";

function conversationRule(
  id: string,
  intent: string,
  patterns: [RegExp, RegExp, RegExp],
  response: string,
  evidence: string[],
): ConversationRule {
  return { id: `dv6-${id}`, intent, patterns, response, evidence };
}

const rules: ConversationRule[] = [
  conversationRule(
    "welcome-back",
    "greeting",
    [/^i am back$/, /^hello again$/, /^back again$/],
    "Welcome back. What would you like to continue with?",
    ["return greeting", "open prompt"],
  ),
  conversationRule(
    "nice-to-meet",
    "social",
    [/^nice to meet you$/, /^pleased to meet you$/, /^good to meet you$/],
    "Nice to meet you too. I’m Lexi, and I’m ready for a question or topic.",
    ["introduction", "social response"],
  ),
  conversationRule(
    "good-day",
    "greeting",
    [/^have a good day$/, /^have a nice day$/, /^enjoy your day$/],
    "Thank you. I hope your day goes well too.",
    ["well wish", "social response"],
  ),
  conversationRule(
    "weekend",
    "small-talk",
    [/^have a good weekend$/, /^enjoy your weekend$/, /^happy weekend$/],
    "Thank you. I hope the weekend gives you useful time for rest or something you enjoy.",
    ["weekend", "well wish"],
  ),
  conversationRule(
    "how-day",
    "small-talk",
    [/^how is your day$/, /^how has your day been$/, /^are you having a good day$/],
    "I do not experience a day, but I’m operating normally and ready to work through yours.",
    ["model boundary", "operating state"],
  ),
  conversationRule(
    "user-good",
    "positive-feeling",
    [/^i am doing well$/, /^i feel good$/, /^today is going well$/],
    "I’m glad things are going well. What would you like to use that momentum for?",
    ["positive state", "forward question"],
  ),
  conversationRule(
    "user-bad",
    "negative-feeling",
    [/^i am not doing well$/, /^i feel bad$/, /^today is going badly$/],
    "I’m sorry the day is going badly. If you want, name the part you can act on first, and I can help break it into a smaller next step.",
    ["negative state", "bounded support"],
  ),
  conversationRule(
    "user-tired",
    "negative-feeling",
    [/^i am tired$/, /^i feel exhausted$/, /^i have no energy$/],
    "That sounds draining. If possible, separate what must be done now from what can wait, then choose one small action or a short rest.",
    ["fatigue", "task reduction"],
  ),
  conversationRule(
    "user-stressed",
    "negative-feeling",
    [/^i am stressed$/, /^i feel overwhelmed$/, /^there is too much to do$/],
    "List the obligations, mark any fixed deadlines, and choose the smallest urgent action. A visible order is easier to manage than one undivided problem.",
    ["stress", "prioritization"],
  ),
  conversationRule(
    "user-frustrated",
    "negative-feeling",
    [/^i am frustrated$/, /^this is frustrating$/, /^i keep getting stuck$/],
    "Name the exact step that fails and what you expected instead. That separates the obstacle from the whole task.",
    ["frustration", "problem isolation"],
  ),
  conversationRule(
    "user-nervous",
    "negative-feeling",
    [/^i am nervous$/, /^i feel anxious about this$/, /^i am worried about it$/],
    "Uncertainty can make a task feel larger. State what is known, what is uncertain, and the next check you can perform.",
    ["uncertainty", "bounded next check"],
  ),
  conversationRule(
    "user-excited",
    "positive-feeling",
    [/^i am excited$/, /^this is exciting$/, /^i cannot wait$/],
    "That energy can be useful. What is the first concrete thing you want to make or learn?",
    ["excitement", "concrete action"],
  ),
  conversationRule(
    "user-sad",
    "negative-feeling",
    [/^i am sad$/, /^i feel down$/, /^i am having a hard day$/],
    "I’m sorry you are having a hard day. I can listen to what happened or help make one practical part of the day simpler.",
    ["sadness", "bounded support"],
  ),
  conversationRule(
    "user-angry",
    "negative-feeling",
    [/^i am angry$/, /^i am mad$/, /^this made me furious$/],
    "Before acting, separate the event, your interpretation, and the outcome you want. That can make the next response more deliberate.",
    ["anger", "event interpretation outcome"],
  ),
  conversationRule(
    "user-confused",
    "clarification-request",
    [/^i am confused about this$/, /^i have lost the thread$/, /^i do not follow this$/],
    "Tell me the last part that still made sense and the first part that did not. I will restart from that boundary.",
    ["confusion", "repair boundary"],
  ),
  conversationRule(
    "user-proud",
    "positive-feeling",
    [/^i am proud of myself$/, /^i did it$/, /^i finally finished$/],
    "That is worth recognizing. Record what helped you finish so the success can become a repeatable method.",
    ["achievement", "repeatable method"],
  ),
  conversationRule(
    "user-lonely",
    "negative-feeling",
    [/^i feel lonely$/, /^i am lonely$/, /^i feel alone$/],
    "I’m sorry you feel alone. A small, specific contact can be easier than solving the whole feeling at once—such as messaging one trusted person.",
    ["loneliness", "small social action"],
  ),
  conversationRule(
    "user-busy",
    "small-talk",
    [/^i am busy$/, /^i have a busy day$/, /^today is packed$/],
    "Then brevity may help. Give me the task and its deadline, and I will keep the response focused.",
    ["busy state", "brief support"],
  ),
  conversationRule(
    "user-hungry",
    "small-talk",
    [/^i am hungry$/, /^i need something to eat$/, /^what should i eat$/],
    "Choose from what is available using your time, dietary needs, and how substantial the meal should be. Name those constraints if you want help comparing options.",
    ["meal constraints", "no inventory assumption"],
  ),
  conversationRule(
    "user-temperature",
    "small-talk",
    [/^i am cold$/, /^i am hot$/, /^the room feels uncomfortable$/],
    "Adjust what you can safely control, such as clothing, airflow, shade, or room settings. I cannot measure the environment from this message.",
    ["temperature", "sensor boundary"],
  ),
  conversationRule(
    "repeat",
    "repetition-request",
    [/^repeat that$/, /^say that again$/, /^can you repeat your answer$/],
    "I do not retain the prior reply inside a new request. Include the subject again, and I will reproduce the supported answer.",
    ["no conversation memory", "subject required"],
  ),
  conversationRule(
    "rephrase",
    "clarification-request",
    [/^rephrase that$/, /^say it another way$/, /^word that differently$/],
    "Include the sentence or subject you want rephrased. I need the material in the current message to transform it.",
    ["rephrase request", "current-message boundary"],
  ),
  conversationRule(
    "slower",
    "format-request",
    [/^go slower$/, /^slow down$/, /^explain it more slowly$/],
    "Ask the subject again with “step by step,” and I will return the ordered form supported by its knowledge record.",
    ["stepwise format", "same-message instruction"],
  ),
  conversationRule(
    "more-detail",
    "format-request",
    [/^give me more detail$/, /^go into more detail$/, /^expand on that$/],
    "Name the subject again and add “in detail.” I do not assume which earlier subject you mean.",
    ["detail format", "explicit subject"],
  ),
  conversationRule(
    "example-request",
    "format-request",
    [/^give me an example$/, /^show me an example$/, /^can i see an example$/],
    "Name the subject whose example you want, and I will use its recorded example rather than inventing one.",
    ["example format", "subject required"],
  ),
  conversationRule(
    "confirm-understanding",
    "confirmation-question",
    [/^do i understand correctly$/, /^is my understanding right$/, /^did i get that right$/],
    "Include your interpretation in the same message. I can then compare its wording with the supported concept.",
    ["confirmation", "statement required"],
  ),
  conversationRule(
    "correction",
    "conversation-repair",
    [/^that is not what i meant$/, /^you misunderstood me$/, /^that answer is wrong for my question$/],
    "State the intended subject and the kind of answer you wanted—definition, purpose, process, example, or comparison—and I will route it explicitly.",
    ["repair", "intent menu"],
  ),
  conversationRule(
    "change-topic",
    "conversation-control",
    [/^let us change the topic$/, /^let's change the topic$/, /^can we talk about something else$/],
    "Yes. Name the new topic directly.",
    ["topic change", "open prompt"],
  ),
  conversationRule(
    "continue",
    "conversation-control",
    [/^continue$/, /^go on$/, /^keep going$/],
    "Name the subject or paste the material to continue. This prototype does not assume hidden conversational state.",
    ["continuation", "state boundary"],
  ),
  conversationRule(
    "stop-topic",
    "conversation-control",
    [/^stop$/, /^that is enough$/, /^let us stop there$/],
    "Understood. I’ll stop that line of explanation.",
    ["stop request", "acknowledgement"],
  ),
  conversationRule(
    "plan-day",
    "task-planning",
    [/^help me plan my day$/, /^make a plan for today$/, /^how should i organize today$/],
    "List fixed commitments, available time, and the three outcomes that matter most. I can then order them without inventing your schedule.",
    ["daily plan", "constraints required"],
  ),
  conversationRule(
    "prioritize",
    "task-planning",
    [/^help me prioritize$/, /^what should i do first$/, /^how do i set priorities$/],
    "Compare tasks by urgency, consequence, effort, and dependency. Do first the task that unlocks important work or prevents the largest near-term cost.",
    ["prioritization", "shared criteria"],
  ),
  conversationRule(
    "focus",
    "task-planning",
    [/^how can i focus$/, /^i keep getting distracted$/, /^help me concentrate$/],
    "Define one visible finish, remove the nearest distraction, and work for a short bounded interval before checking progress.",
    ["focus", "bounded work interval"],
  ),
  conversationRule(
    "procrastination",
    "task-planning",
    [/^i am procrastinating$/, /^i keep (?:putting it off|procrastinating)$/, /^how do i stop procrastinating$/],
    "Reduce the start until it takes less than five minutes: open the file, write one heading, or collect one required item.",
    ["procrastination", "small start"],
  ),
  conversationRule(
    "organize",
    "task-planning",
    [/^help me get organized$/, /^how should i organize this$/, /^everything is disorganized$/],
    "Separate inputs, active work, waiting items, and finished material. Give each group one clear location and review point.",
    ["organization", "state groups"],
  ),
  conversationRule(
    "study-plan",
    "learning",
    [/^help me make a study plan$/, /^how should i plan my studying$/, /^i need a study schedule$/],
    "Name the subject, deadline, available sessions, and required level. A useful plan alternates learning, recall, practice, and review.",
    ["study plan", "learning cycle"],
  ),
  conversationRule(
    "quiz-me",
    "learning",
    [/^quiz me$/, /^test my knowledge$/, /^ask me practice questions$/],
    "Name the subject and difficulty. I can ask bounded questions only for material represented in my knowledge records.",
    ["quiz", "subject and difficulty"],
  ),
  conversationRule(
    "brainstorm",
    "creativity",
    [/^help me brainstorm$/, /^give me some ideas$/, /^i need ideas$/],
    "State the goal, audience, constraints, and how many ideas you need. Those boundaries make mechanical variation more useful.",
    ["brainstorming", "constraints"],
  ),
  conversationRule(
    "writing-start",
    "simple-request",
    [/^help me start writing$/, /^i do not know how to begin writing$/, /^how do i start this document$/],
    "Write one sentence naming the audience, purpose, and main point. Then list the evidence or sections needed to support it.",
    ["writing", "audience purpose point"],
  ),
  conversationRule(
    "troubleshoot",
    "problem-solving",
    [/^help me troubleshoot$/, /^something is not working$/, /^how do i find the problem$/],
    "Record the expected behavior, actual behavior, last known working state, and smallest reproducible case. Change one variable at a time.",
    ["troubleshooting", "controlled isolation"],
  ),
  conversationRule(
    "pros-cons",
    "decision-support",
    [/^help me list pros and cons$/, /^what are the pros and cons$/, /^make a pros and cons list$/],
    "Name the option and the criteria that matter. Without that context, a generic list could invent irrelevant advantages or drawbacks.",
    ["pros and cons", "criteria required"],
  ),
  conversationRule(
    "goal-plan",
    "task-planning",
    [/^help me reach my goal$/, /^how do i achieve a goal$/, /^turn my goal into a plan$/],
    "Define the observable finish, current state, constraints, and next checkpoint. Then choose the smallest action that changes the current state.",
    ["goal", "checkpoint", "next action"],
  ),
  conversationRule(
    "break-task",
    "task-planning",
    [/^break this task down$/, /^make this task smaller$/, /^this task is too big$/],
    "State the task and final deliverable. I will separate preparation, production, verification, and completion steps.",
    ["task decomposition", "deliverable required"],
  ),
  conversationRule(
    "check-work",
    "verification",
    [/^check my work$/, /^can you verify this$/, /^is this correct$/],
    "Include the work, source assumptions, and expected result. I cannot verify material that is not present in the current message.",
    ["verification", "evidence required"],
  ),
  conversationRule(
    "explain-choice",
    "decision-support",
    [/^explain your choice$/, /^why did you choose that$/, /^what was your reasoning$/],
    "Open “Why this response” to inspect the matched context, evidence terms, and selected structure. I do not have a hidden private rationale.",
    ["public trace", "no hidden rationale"],
  ),
  conversationRule(
    "conversation-starter",
    "conversation-request",
    [/^start a conversation$/, /^give me a conversation starter$/, /^what should we talk about$/],
    "Choose one: a concept you recently encountered, a decision you are making, or a process you want to understand better.",
    ["conversation starter", "three choices"],
  ),
  conversationRule(
    "fun-fact",
    "conversation-request",
    [/^tell me a fun fact$/, /^give me an interesting fact$/, /^share a fact$/],
    "A language-model fact: tokenization can split one written word into several processing units, so a token is not always the same as a word.",
    ["recorded fact", "tokenization"],
  ),
  conversationRule(
    "riddle",
    "humor",
    [/^tell me a riddle$/, /^give me a riddle$/, /^do you know a riddle$/],
    "What has many keys but opens no locks? A keyboard.",
    ["reviewed riddle", "keyboard"],
  ),
  conversationRule(
    "word-game",
    "conversation-request",
    [/^play a word game$/, /^let us play with words$/, /^give me a word challenge$/],
    "Name a word, and try to give a synonym, antonym, and sentence using it. I can compare those with my dictionary and thesaurus paths.",
    ["word game", "synonym antonym sentence"],
  ),
  conversationRule(
    "topic-suggestion",
    "conversation-request",
    [/^suggest a topic$/, /^give me something to learn$/, /^what can i learn about$/],
    "Try one of these: attention mechanisms, supply and demand, homeostasis, graph theory, or critical thinking.",
    ["technical topics", "learning menu"],
  ),
  conversationRule(
    "congratulate",
    "social",
    [/^congratulate me$/, /^say congratulations$/, /^i have good news$/],
    "Congratulations. Name what happened if you want a response specific to the achievement.",
    ["congratulations", "specific context"],
  ),
  conversationRule(
    "sympathy",
    "social",
    [/^i have bad news$/, /^something difficult happened$/, /^i had a loss$/],
    "I’m sorry. If you want to describe it, I can acknowledge what happened or help with one practical next step.",
    ["sympathy", "bounded support"],
  ),
  conversationRule(
    "agree",
    "agreement",
    [/^i agree with you$/, /^that sounds right$/, /^yes that makes sense$/],
    "Understood. The supported point is clear; we can test it with an example or move to the next question.",
    ["agreement", "next step"],
  ),
  conversationRule(
    "disagree",
    "disagreement",
    [/^i disagree with you$/, /^i do not think that is right$/, /^that does not sound correct$/],
    "That is useful feedback. State the claim you dispute and the evidence or interpretation you prefer, and I will compare them explicitly.",
    ["disagreement", "claim and evidence"],
  ),
  conversationRule(
    "compliment-lexi",
    "compliment",
    [/^you are helpful$/, /^you did a good job$/, /^that was a good answer$/],
    "Thank you. The best confirmation is whether the answer matched your question and its evidence remained inspectable.",
    ["compliment", "traceable quality"],
  ),
  conversationRule(
    "insult-lexi",
    "conversation-repair",
    [/^you are useless$/, /^you are stupid$/, /^that was terrible$/],
    "The response missed your need. Name the intended subject and answer type, and I will attempt a more exact route.",
    ["repair", "non-retaliation"],
  ),
  conversationRule(
    "welcome",
    "thanks",
    [/^you are welcome$/, /^no problem$/, /^anytime$/],
    "Acknowledged.",
    ["social acknowledgement"],
  ),
  conversationRule(
    "patience",
    "format-request",
    [/^be patient with me$/, /^i am learning slowly$/, /^please take your time$/],
    "That is fine. Ask one subject at a time and add “step by step” when you want the ordered explanation form.",
    ["patience", "stepwise option"],
  ),
  conversationRule(
    "honesty",
    "certainty-check",
    [/^be honest with me$/, /^tell me if you do not know$/, /^do not make anything up$/],
    "Agreed. I will use recorded knowledge or state that the connection is unsupported; the response trace shows which path was used.",
    ["honesty boundary", "public trace"],
  ),
  conversationRule(
    "capability-menu",
    "capability",
    [/^what kinds of questions can i ask$/, /^give me examples of what you can answer$/, /^show me your capabilities$/],
    "You can ask for definitions, purposes, mechanisms, importance, examples, components, related concepts, summaries, learning paths, comparisons, simple calculations, and bounded logical inferences.",
    ["capability menu", "supported intents"],
  ),
];

export function matchDv6Conversation(normalized: string): PackResponse | undefined {
  const rule = rules.find((candidate) =>
    candidate.patterns.some((pattern) => pattern.test(normalized)),
  );
  if (!rule) return undefined;

  return {
    text: rule.response,
    intent: rule.intent,
    recordIds: [`conversation:${rule.id}`],
    evidence: rule.evidence,
    structureId: `extended-conversation:${rule.id}`,
    confidence: 1,
  };
}

export const dv6ConversationPatternCount = rules.reduce(
  (sum, rule) => sum + rule.patterns.length,
  0,
);
