import type { PackFocus } from "./types";

export type QuestionFrame = {
  id: string;
  focus: PackFocus;
  pattern: RegExp;
};

function frames(
  focus: PackFocus,
  definitions: Array<[string, RegExp]>,
): QuestionFrame[] {
  return definitions.map(([id, pattern]) => ({ id: `${focus}-${id}`, focus, pattern }));
}

export const singleSubjectFrames: QuestionFrame[] = [
  ...frames("definition", [
    ["what-is", /^what is (.+)$/],
    ["what-are", /^what are (.+)$/],
    ["what-exactly-is", /^what exactly is (.+)$/],
    ["what-is-exactly", /^what is (.+?) exactly$/],
    ["what-meant-by", /^what is meant by (.+)$/],
    ["what-mean", /^what does (.+?) mean$/],
    ["how-define", /^how would you define (.+)$/],
    ["define", /^define (.+)$/],
    ["explain", /^explain (.+)$/],
    ["describe", /^describe (.+)$/],
    ["introduce", /^introduce (.+)$/],
    ["tell-about", /^tell me about (.+)$/],
    ["tell-what", /^tell me what (.+?) is$/],
    ["explanation", /^give me an explanation of (.+)$/],
    ["overview", /^give me an overview of (.+)$/],
    ["provide-explanation", /^provide an explanation of (.+)$/],
    ["help-understand", /^help me understand (.+)$/],
    ["help-learn", /^help me learn about (.+)$/],
    ["want-know", /^i want to know about (.+)$/],
    ["would-like-know", /^i would like to know about (.+)$/],
    ["want-learn", /^i want to learn about (.+)$/],
    ["curious-about", /^i am curious about (.+)$/],
    ["can-explain", /^can you explain (.+)$/],
    ["could-explain", /^could you explain (.+)$/],
    ["would-explain", /^would you explain (.+)$/],
    ["will-explain", /^will you explain (.+)$/],
    ["can-tell", /^can you tell me about (.+)$/],
    ["could-tell", /^could you tell me about (.+)$/],
    ["can-define", /^can you define (.+)$/],
    ["know-what", /^do you know what (.+?) is$/],
    ["know-about", /^what do you know about (.+)$/],
    ["meaning-of", /^meaning of (.+)$/],
    ["definition-of", /^definition of (.+)$/],
    ["concept-of", /^explain the concept of (.+)$/],
  ]),
  ...frames("purpose", [
    ["used-for", /^what is (.+?) used for$/],
    ["are-used-for", /^what are (.+?) used for$/],
    ["what-for", /^what is (.+?) for$/],
    ["does-do", /^what does (.+?) do$/],
    ["do-do", /^what do (.+?) do$/],
    ["purpose-of", /^what is the purpose of (.+)$/],
    ["main-purpose", /^what is the main purpose of (.+)$/],
    ["use-of", /^what is the use of (.+)$/],
    ["uses-of", /^what are the uses of (.+)$/],
    ["why-use", /^why do we use (.+)$/],
    ["why-someone-use", /^why would someone use (.+)$/],
    ["tell-purpose", /^tell me the purpose of (.+)$/],
    ["explain-purpose", /^explain the purpose of (.+)$/],
    ["describe-purpose", /^describe the purpose of (.+)$/],
    ["can-use", /^what can (.+?) be used for$/],
    ["helps-with", /^what does (.+?) help with$/],
    ["role-of", /^what is the role of (.+)$/],
    ["function-of", /^what is the function of (.+)$/],
  ]),
  ...frames("mechanism", [
    ["how-work", /^how does (.+?) work$/],
    ["how-do-work", /^how do (.+?) work$/],
    ["how-exactly", /^how exactly does (.+?) work$/],
    ["how-happen", /^how does (.+?) happen$/],
    ["how-do-happen", /^how do (.+?) happen$/],
    ["how-made", /^how is (.+?) made$/],
    ["how-are-made", /^how are (.+?) made$/],
    ["process-behind", /^what is the process behind (.+)$/],
    ["process-of", /^what is the process of (.+)$/],
    ["explain-how", /^explain how (.+?) works$/],
    ["describe-how", /^describe how (.+?) works$/],
    ["can-explain-how", /^can you explain how (.+?) works$/],
    ["could-explain-how", /^could you explain how (.+?) works$/],
    ["would-explain-how", /^would you explain how (.+?) works$/],
    ["steps-behind", /^what are the steps behind (.+)$/],
    ["operates", /^how does (.+?) operate$/],
    ["functions", /^how does (.+?) function$/],
    ["mechanism-of", /^what is the mechanism of (.+)$/],
  ]),
  ...frames("importance", [
    ["why-important", /^why is (.+?) important$/],
    ["why-are-important", /^why are (.+?) important$/],
    ["why-matter", /^why does (.+?) matter$/],
    ["why-do-matter", /^why do (.+?) matter$/],
    ["importance-of", /^what is the importance of (.+)$/],
    ["significance-of", /^what is the significance of (.+)$/],
    ["explain-why", /^explain why (.+?) is important$/],
    ["describe-why", /^describe why (.+?) is important$/],
    ["what-makes", /^what makes (.+?) important$/],
    ["why-care", /^why should i care about (.+)$/],
    ["worth-knowing", /^why is (.+?) worth knowing$/],
    ["value-of", /^what is the value of (.+)$/],
    ["benefit-understanding", /^what is the benefit of understanding (.+)$/],
    ["relevant", /^why is (.+?) relevant$/],
    ["need-know", /^why do i need to know about (.+)$/],
    ["importance-tell", /^tell me why (.+?) matters$/],
  ]),
  ...frames("example", [
    ["give-example", /^give me an example of (.+)$/],
    ["give-one", /^give me one example of (.+)$/],
    ["show-example", /^show me an example of (.+)$/],
    ["what-example", /^what is an example of (.+)$/],
    ["what-examples", /^what are examples of (.+)$/],
    ["some-examples", /^what are some examples of (.+)$/],
    ["can-give", /^can you give me an example of (.+)$/],
    ["could-give", /^could you give me an example of (.+)$/],
    ["provide-example", /^provide an example of (.+)$/],
    ["illustrate", /^illustrate (.+?) with an example$/],
    ["real-example", /^what is a real example of (.+)$/],
    ["simple-example", /^give me a simple example of (.+)$/],
    ["example-only", /^example of (.+)$/],
    ["show-in-use", /^show me (.+?) in use$/],
  ]),
  ...frames("components", [
    ["parts-of", /^what are the parts of (.+)$/],
    ["components-of", /^what are the components of (.+)$/],
    ["elements-of", /^what are the elements of (.+)$/],
    ["consist-of", /^what does (.+?) consist of$/],
    ["do-consist", /^what do (.+?) consist of$/],
    ["list-parts", /^list the parts of (.+)$/],
    ["list-components", /^list the components of (.+)$/],
    ["name-parts", /^name the parts of (.+)$/],
    ["made-of", /^what is (.+?) made of$/],
    ["are-made-of", /^what are (.+?) made of$/],
    ["contains", /^what does (.+?) contain$/],
    ["include", /^what does (.+?) include$/],
    ["break-down", /^break down (.+)$/],
    ["main-elements", /^what are the main elements in (.+)$/],
  ]),
  ...frames("related", [
    ["related-to", /^what is (.+?) related to$/],
    ["are-related-to", /^what are (.+?) related to$/],
    ["concepts-related", /^what concepts are related to (.+)$/],
    ["topics-related", /^what topics are related to (.+)$/],
    ["goes-with", /^what goes with (.+)$/],
    ["list-topics", /^list topics related to (.+)$/],
    ["name-topics", /^name topics related to (.+)$/],
    ["connected-to", /^what is connected to (.+)$/],
    ["similar-concepts", /^what concepts are similar to (.+)$/],
    ["learn-next", /^what should i learn after (.+)$/],
    ["associated-with", /^what is associated with (.+)$/],
    ["closest-concepts", /^what are the closest concepts to (.+)$/],
  ]),
  ...frames("summary", [
    ["summarize", /^summarize (.+)$/],
    ["summary-of", /^give me a summary of (.+)$/],
    ["quick-summary", /^give me a quick summary of (.+)$/],
    ["key-points", /^what are the key points of (.+)$/],
    ["main-idea", /^what is the main idea of (.+)$/],
    ["overview", /^provide a summary of (.+)$/],
    ["in-nutshell", /^what is (.+?) in a nutshell$/],
    ["essentials", /^what are the essentials of (.+)$/],
    ["basics", /^what are the basics of (.+)$/],
    ["short-version", /^what is the short version of (.+)$/],
    ["sum-up", /^sum up (.+)$/],
    ["big-picture", /^give me the big picture of (.+)$/],
  ]),
  ...frames("learning", [
    ["how-learn", /^how can i learn (.+)$/],
    ["how-study", /^how should i study (.+)$/],
    ["where-start", /^where should i start with (.+)$/],
    ["begin-learning", /^how do i begin learning (.+)$/],
    ["teach-myself", /^how can i teach myself (.+)$/],
    ["first-learn", /^what should i learn first about (.+)$/],
    ["beginner-know", /^what should a beginner know about (.+)$/],
    ["approach-learning", /^how should i approach learning (.+)$/],
    ["study-order", /^what order should i study (.+?) in$/],
    ["foundation", /^what is the foundation for learning (.+)$/],
  ]),
];

export const comparisonFrames: QuestionFrame[] = [
  ...frames("comparison", [
    ["difference-between", /^what is the difference between (.+?) and (.+)$/],
    ["differences-between", /^what are the differences between (.+?) and (.+)$/],
    ["different-from", /^how is (.+?) different from (.+)$/],
    ["differ-from", /^how does (.+?) differ from (.+)$/],
    ["compare-and", /^compare (.+?) and (.+)$/],
    ["compare-with", /^compare (.+?) with (.+)$/],
    ["contrast-and", /^contrast (.+?) and (.+)$/],
    ["contrast-with", /^contrast (.+?) with (.+)$/],
    ["distinguish", /^distinguish between (.+?) and (.+)$/],
    ["what-separates", /^what separates (.+?) from (.+)$/],
    ["same-or-different", /^are (.+?) and (.+?) the same or different$/],
  ]),
  ...frames("similarity", [
    ["similar-about", /^what is similar about (.+?) and (.+)$/],
    ["similarities-between", /^what are the similarities between (.+?) and (.+)$/],
    ["have-common", /^what do (.+?) and (.+?) have in common$/],
    ["how-similar", /^how similar are (.+?) and (.+)$/],
    ["related-how", /^how are (.+?) and (.+?) related$/],
  ]),
];

export const extendedQuestionFrameCount =
  singleSubjectFrames.length + comparisonFrames.length;
