import type { KnowledgeTopic } from "../types";

type TechnicalSeed = Omit<KnowledgeTopic, "aliases"> & {
  aliases: [string, string];
};

function compileTechnicalTopics(seeds: TechnicalSeed[]): KnowledgeTopic[] {
  return seeds.map((seed, index) => ({
    ...seed,
    aliases: [
      `${seed.term} basics`,
      `basic ${seed.term}`,
      `${seed.term} fundamentals`,
      ...seed.aliases,
    ].slice(0, index < 66 ? 5 : 4),
  }));
}

const seeds: TechnicalSeed[] = [
  // Engineering and software systems: 20 topics.
  {
    id: "tech-api",
    term: "API",
    aliases: ["application programming interface", "software interface"],
    category: "engineering",
    definition: "a documented interface through which software components request data or operations from one another",
    purpose: "let independently built programs communicate through agreed inputs and outputs",
    mechanism: "a caller sends a structured request to an exposed operation, which validates the request and returns a structured result",
    importance: "it separates implementation details from the contract other software depends on",
    example: "a weather application requesting forecast data from a weather service API",
    components: ["operations", "request parameters", "response formats", "authentication rules"],
    related: ["software", "a network protocol", "a distributed system"],
  },
  {
    id: "tech-data-structure",
    term: "data structure",
    aliases: ["information structure", "organized data container"],
    category: "computing",
    definition: "a defined way of organizing data so particular operations can be performed predictably",
    purpose: "store and retrieve information with behavior suited to a task",
    mechanism: "values are arranged according to rules that determine insertion, lookup, traversal, and removal",
    importance: "the chosen organization strongly affects the speed and clarity of an algorithm",
    example: "a queue holding print jobs in the order they arrived",
    components: ["stored values", "relationships", "allowed operations", "invariants"],
    related: ["an algorithm", "computational complexity", "programming"],
  },
  {
    id: "tech-cybersecurity",
    term: "cybersecurity",
    aliases: ["computer security", "digital security"],
    category: "engineering",
    definition: "the practice of protecting digital systems, networks, and information from unauthorized access or disruption",
    purpose: "reduce the likelihood and impact of digital threats",
    mechanism: "people combine prevention, detection, access control, monitoring, and recovery procedures",
    importance: "digital services depend on the confidentiality, integrity, and availability of their systems",
    example: "requiring multi-factor authentication before an administrator can change a server",
    components: ["identity control", "secure configuration", "monitoring", "incident response"],
    related: ["encryption", "risk management", "a computer network"],
  },
  {
    id: "tech-cloud-computing",
    term: "cloud computing",
    aliases: ["cloud services", "remote computing infrastructure"],
    category: "engineering",
    definition: "the delivery of shared computing resources over a network as configurable services",
    purpose: "provide computing capacity without every user owning and operating all underlying hardware",
    mechanism: "providers pool physical systems and allocate virtualized processing, storage, and networking on demand",
    importance: "it makes infrastructure easier to scale, automate, and access from different locations",
    example: "running a website on rented virtual servers that expand during heavy traffic",
    components: ["compute", "storage", "networking", "service management"],
    related: ["a virtual machine", "containerization", "a distributed system"],
  },
  {
    id: "tech-compiler",
    term: "compiler",
    aliases: ["code compiler", "language translator"],
    category: "computing",
    definition: "a program that translates source code into another executable or intermediate representation",
    purpose: "convert human-authored programming notation into instructions a target system can run",
    mechanism: "source text is parsed, checked, transformed, optimized, and emitted in a target form",
    importance: "it connects programming languages to hardware while detecting many structural errors",
    example: "turning a C program into machine instructions for a processor",
    components: ["lexer", "parser", "semantic analysis", "code generator"],
    related: ["programming", "computer architecture", "software testing"],
  },
  {
    id: "tech-software-testing",
    term: "software testing",
    aliases: ["program testing", "software verification"],
    category: "engineering",
    definition: "the systematic checking of software behavior against stated expectations",
    purpose: "find defects and provide evidence about whether a system behaves as required",
    mechanism: "selected inputs are executed under controlled conditions and actual results are compared with expected results",
    importance: "software can fail in combinations its authors did not notice during implementation",
    example: "checking that a payment form rejects an expired card without losing entered information",
    components: ["test cases", "expected results", "execution environment", "defect reports"],
    related: ["quality assurance", "programming", "version control"],
  },
  {
    id: "tech-version-control",
    term: "version control",
    aliases: ["source control", "revision control"],
    category: "engineering",
    definition: "a system for recording and coordinating changes to files over time",
    purpose: "preserve history, support collaboration, and allow known states to be recovered",
    mechanism: "changes are stored as identified revisions linked through branches and merges",
    importance: "it makes complex collaborative work traceable and reversible",
    example: "using Git commits to review and restore changes to a program",
    components: ["repository", "revision", "branch", "merge"],
    related: ["software", "teamwork", "software testing"],
  },
  {
    id: "tech-sensor",
    term: "sensor",
    aliases: ["measurement sensor", "physical detector"],
    category: "engineering",
    definition: "a device that converts a physical condition into a signal that can be measured",
    purpose: "allow a system to observe its environment or internal state",
    mechanism: "a sensing element responds to a physical quantity and a transducer produces a corresponding signal",
    importance: "automatic systems need measurements before they can monitor or control real conditions",
    example: "a temperature sensor changing electrical resistance as a room becomes warmer",
    components: ["sensing element", "transducer", "signal conditioning", "calibration"],
    related: ["measurement", "signal processing", "a control system"],
  },
  {
    id: "tech-control-system",
    term: "control system",
    aliases: ["automatic control", "feedback controller"],
    category: "engineering",
    definition: "a system that adjusts a process so its measured behavior approaches a desired state",
    purpose: "keep a changing process stable or guide it toward a target",
    mechanism: "a controller compares measured output with a reference and changes an input according to the resulting error",
    importance: "feedback lets machines correct disturbances instead of relying on fixed actions",
    example: "a thermostat turning heating on when measured temperature falls below its setting",
    components: ["reference", "controller", "process", "feedback measurement"],
    related: ["a sensor", "robotics", "signal processing"],
  },
  {
    id: "tech-circuit",
    term: "electrical circuit",
    aliases: ["electric circuit", "connected electrical path"],
    category: "engineering",
    definition: "an interconnected path through which electric current can flow and perform a function",
    purpose: "move and transform electrical energy or signals",
    mechanism: "voltage drives current through connected components whose properties shape the circuit behavior",
    importance: "nearly all electronic devices depend on controlled relationships between voltage, current, and components",
    example: "a battery, switch, resistor, and lamp connected in a closed loop",
    components: ["source", "conductive path", "load", "control elements"],
    related: ["electricity", "a microprocessor", "signal processing"],
  },
  {
    id: "tech-microprocessor",
    term: "microprocessor",
    aliases: ["central processing chip", "processor chip"],
    category: "engineering",
    definition: "an integrated electronic processor that executes encoded instructions",
    purpose: "perform arithmetic, logic, and control operations for a computing system",
    mechanism: "a clock coordinates instruction fetching, decoding, execution, and movement of data through registers",
    importance: "it provides programmable control in computers and embedded devices",
    example: "a processor repeatedly executing instructions for a phone application",
    components: ["control unit", "arithmetic logic unit", "registers", "cache"],
    related: ["computer hardware", "computer architecture", "a compiler"],
  },
  {
    id: "tech-robotics",
    term: "robotics",
    aliases: ["robot engineering", "robotic systems"],
    category: "engineering",
    definition: "the field concerned with designing machines that sense, decide, and act in the physical world",
    purpose: "automate or assist physical tasks through programmable machines",
    mechanism: "sensors provide measurements, control software selects actions, and actuators produce motion",
    importance: "it combines computation with physical action in environments that can change",
    example: "a warehouse robot locating a shelf and carrying a container to a packing station",
    components: ["sensors", "controller", "actuators", "mechanical structure"],
    related: ["a control system", "artificial intelligence", "a sensor"],
  },
  {
    id: "tech-cad",
    term: "computer-aided design",
    aliases: ["CAD", "digital engineering design"],
    category: "engineering",
    definition: "the use of software to create and analyze precise digital models of designed objects",
    purpose: "represent dimensions, geometry, and engineering constraints before physical production",
    mechanism: "designers construct parameterized geometry that software displays, measures, and revises",
    importance: "digital models make technical changes easier to inspect, communicate, and reproduce",
    example: "modeling a mechanical bracket with exact hole positions before machining it",
    components: ["geometry model", "dimensions", "constraints", "drawing or simulation tools"],
    related: ["engineering", "computer graphics", "quality assurance"],
  },
  {
    id: "tech-signal-processing",
    term: "signal processing",
    aliases: ["signal analysis", "digital signal processing"],
    category: "engineering",
    definition: "the analysis and transformation of measured signals to extract or modify information",
    purpose: "reduce noise, reveal patterns, compress data, or prepare signals for decisions",
    mechanism: "mathematical operations transform a signal in time, frequency, or another representation",
    importance: "raw measurements often contain noise and structure that cannot be used directly",
    example: "filtering background noise from a recorded voice",
    components: ["signal", "sampling", "transform or filter", "output representation"],
    related: ["a sensor", "linear algebra", "a control system"],
  },
  {
    id: "tech-distributed-system",
    term: "distributed system",
    aliases: ["distributed computing system", "multi-node system"],
    category: "engineering",
    definition: "a collection of networked computers that coordinate to provide one larger service",
    purpose: "share work, data, or reliability across multiple machines",
    mechanism: "independent nodes exchange messages and follow protocols despite delay or partial failure",
    importance: "large services must continue operating when one machine is insufficient or unavailable",
    example: "several database servers replicating records across locations",
    components: ["nodes", "network messages", "coordination protocol", "failure handling"],
    related: ["cloud computing", "a network protocol", "a database"],
  },
  {
    id: "tech-computer-architecture",
    term: "computer architecture",
    aliases: ["processor architecture", "computer system design"],
    category: "engineering",
    definition: "the structured design of a computer's instruction behavior and major hardware organization",
    purpose: "define how programs, processors, memory, and input-output systems work together",
    mechanism: "an instruction set and hardware pathways determine how data and operations move through the machine",
    importance: "architecture shapes performance, compatibility, energy use, and compiler design",
    example: "an instruction set defining how a processor loads values and adds them",
    components: ["instruction set", "processor", "memory hierarchy", "input-output system"],
    related: ["a microprocessor", "computer hardware", "a compiler"],
  },
  {
    id: "tech-containerization",
    term: "containerization",
    aliases: ["software containers", "application containers"],
    category: "engineering",
    definition: "the packaging of an application with its dependencies in an isolated operating-system process environment",
    purpose: "make software run consistently across compatible hosts",
    mechanism: "the host kernel isolates process resources while an image supplies the application's files and configuration",
    importance: "repeatable packages simplify deployment and reduce environment differences",
    example: "shipping a web service as a container image used in testing and production",
    components: ["image", "container runtime", "isolated process", "configuration"],
    related: ["cloud computing", "an operating system", "a virtual machine"],
  },
  {
    id: "tech-virtual-machine",
    term: "virtual machine",
    aliases: ["VM", "virtualized computer"],
    category: "engineering",
    definition: "a software-defined computer environment that behaves like an independent physical machine",
    purpose: "run isolated operating systems on shared physical hardware",
    mechanism: "a hypervisor maps virtual processors, memory, storage, and devices onto host resources",
    importance: "virtualization improves isolation, portability, and hardware utilization",
    example: "running a Linux server as a guest on a larger physical host",
    components: ["virtual processor", "virtual memory", "virtual storage", "hypervisor"],
    related: ["cloud computing", "containerization", "an operating system"],
  },
  {
    id: "tech-file-system",
    term: "file system",
    aliases: ["filesystem", "storage organization system"],
    category: "computing",
    definition: "the rules and data structures an operating system uses to name, store, and retrieve files",
    purpose: "organize persistent data into accessible files and directories",
    mechanism: "metadata maps human-readable paths to allocated storage blocks and access permissions",
    importance: "reliable storage requires consistent naming, allocation, protection, and recovery",
    example: "a directory entry linking a file name to its stored data blocks",
    components: ["files", "directories", "metadata", "storage allocation"],
    related: ["an operating system", "data structure", "computer hardware"],
  },
  {
    id: "tech-network-protocol",
    term: "network protocol",
    aliases: ["communication protocol", "network communication rules"],
    category: "engineering",
    definition: "a shared set of rules for formatting and exchanging messages between networked systems",
    purpose: "let independent devices interpret one another's communication consistently",
    mechanism: "participants encode messages, maintain state, and respond according to an agreed sequence",
    importance: "communication fails when participants disagree about message meaning or order",
    example: "HTTP defining how a browser requests a page and how a server responds",
    components: ["message format", "state rules", "error behavior", "transport assumptions"],
    related: ["a computer network", "API", "a distributed system"],
  },

  // Artificial intelligence and data practice: 20 topics.
  {
    id: "data-neural-network",
    term: "neural network",
    aliases: ["artificial neural network", "layered learning network"],
    category: "data-science",
    definition: "a parameterized computing structure made of connected layers that transform numerical inputs",
    purpose: "learn complex mappings from examples rather than relying only on manually written rules",
    mechanism: "training adjusts connection weights so the network's outputs better match target examples",
    importance: "layered transformations can represent patterns that are difficult to specify directly",
    example: "a network mapping image pixels to probabilities for object categories",
    components: ["input representation", "layers", "weights", "activation functions"],
    related: ["machine learning", "training data", "inference"],
  },
  {
    id: "data-language-model",
    term: "language model",
    aliases: ["statistical language model", "model of language sequences"],
    category: "data-science",
    definition: "a system that assigns scores or probabilities to sequences of language units",
    purpose: "represent patterns in language so likely continuations or interpretations can be estimated",
    mechanism: "the model uses learned or counted relationships between preceding units and possible next units",
    importance: "many language tasks depend on estimating which sequences fit a context",
    example: "ranking likely next words after a partial sentence",
    components: ["language units", "context representation", "scoring function", "vocabulary"],
    related: ["tokenization", "a large language model", "inference"],
  },
  {
    id: "data-large-language-model",
    term: "large language model",
    aliases: ["LLM", "large-scale language model"],
    category: "data-science",
    definition: "a language model with many learned parameters trained on a large collection of text",
    purpose: "generalize statistical language patterns across many prompts and tasks",
    mechanism: "a transformer commonly maps tokens through attention and layered numerical transformations to score continuations",
    importance: "scale can produce broad linguistic flexibility, although outputs remain dependent on training and inference behavior",
    example: "a transformer predicting a sequence of response tokens from a prompt",
    components: ["tokenizer", "embeddings", "transformer layers", "output probabilities"],
    related: ["a language model", "an attention mechanism", "transformer architecture"],
  },
  {
    id: "data-tokenization",
    term: "tokenization",
    aliases: ["text tokenization", "language unit splitting"],
    category: "data-science",
    definition: "the conversion of text into a sequence of defined units that a language system can process",
    purpose: "give algorithms consistent symbolic or numerical input units",
    mechanism: "rules or a learned vocabulary segment characters into words, subwords, or other tokens",
    importance: "the chosen units affect vocabulary size, unknown terms, and sequence length",
    example: "splitting an uncommon word into several known subword pieces",
    components: ["input text", "segmentation rules", "token vocabulary", "token identifiers"],
    related: ["a word", "a language model", "embedding"],
  },
  {
    id: "data-embedding",
    term: "embedding",
    aliases: ["vector embedding", "learned vector representation"],
    category: "data-science",
    definition: "a numerical vector used to represent an item in a space where positions encode learned relationships",
    purpose: "turn discrete items into values that numerical models can compare and transform",
    mechanism: "training adjusts vector coordinates so items useful in similar contexts receive related representations",
    importance: "continuous representations support similarity, grouping, and downstream prediction",
    example: "representing words as vectors used by a language model",
    components: ["item identifier", "vector dimensions", "training objective", "distance measure"],
    related: ["vector", "tokenization", "machine learning"],
  },
  {
    id: "data-attention",
    term: "attention mechanism",
    aliases: ["model attention", "weighted context mechanism"],
    category: "data-science",
    definition: "a computation that forms a context-dependent mixture of information by weighting candidate elements",
    purpose: "let a model emphasize different parts of its input for each output position",
    mechanism: "queries are compared with keys to produce weights that combine corresponding value vectors",
    importance: "relevant context can be selected dynamically instead of compressed into one fixed state",
    example: "a pronoun representation assigning more weight to a likely earlier noun",
    components: ["queries", "keys", "values", "attention weights"],
    related: ["transformer architecture", "embedding", "a large language model"],
  },
  {
    id: "data-transformer",
    term: "transformer architecture",
    aliases: ["transformer model", "attention-based model"],
    category: "data-science",
    definition: "a layered neural architecture built around attention and position-wise transformations",
    purpose: "process sequences while relating elements across different positions",
    mechanism: "each layer combines attention, feed-forward transformations, residual paths, and normalization",
    importance: "parallel sequence processing and flexible context relationships support large-scale language modeling",
    example: "several transformer layers turning prompt-token vectors into next-token scores",
    components: ["attention", "feed-forward layers", "residual connections", "normalization"],
    related: ["an attention mechanism", "a neural network", "a large language model"],
  },
  {
    id: "data-training-data",
    term: "training data",
    aliases: ["model training examples", "learning dataset"],
    category: "data-science",
    definition: "the recorded examples used to fit the adjustable parameters or rules of a model",
    purpose: "provide evidence from which a system can learn statistical relationships",
    mechanism: "an optimization procedure repeatedly compares model outputs with objectives derived from examples",
    importance: "coverage, quality, labels, and bias in examples shape what a model can learn",
    example: "labelled messages used to train a spam classifier",
    components: ["examples", "features", "targets or objectives", "sampling process"],
    related: ["machine learning", "data governance", "model evaluation"],
  },
  {
    id: "data-inference",
    term: "inference",
    aliases: ["model inference", "trained-model execution"],
    category: "data-science",
    definition: "the use of a fitted model to produce an output for new input",
    purpose: "apply learned parameters without repeating the full training process",
    mechanism: "input is transformed through the fixed model to compute scores, predictions, or generated units",
    importance: "runtime behavior determines the speed, cost, and practical reliability of a deployed model",
    example: "a trained classifier assigning a category to a new message",
    components: ["new input", "fixed parameters", "forward computation", "output interpretation"],
    related: ["machine learning", "model evaluation", "a language model"],
  },
  {
    id: "data-classification",
    term: "classification",
    aliases: ["category prediction", "class assignment"],
    category: "data-science",
    definition: "the task of assigning an observation to one or more defined categories",
    purpose: "turn measured features into discrete labels useful for decisions",
    mechanism: "a rule or fitted model scores candidate classes and applies a decision boundary",
    importance: "many practical decisions require a bounded category rather than an unrestricted description",
    example: "classifying an email as wanted mail or spam",
    components: ["features", "class labels", "decision rule", "evaluation data"],
    related: ["machine learning", "regression analysis", "model evaluation"],
  },
  {
    id: "data-regression",
    term: "regression analysis",
    aliases: ["regression model", "numeric prediction analysis"],
    category: "data-science",
    definition: "a family of methods for describing or predicting a numerical outcome from explanatory variables",
    purpose: "estimate how an outcome changes with measured inputs",
    mechanism: "parameters are fitted to reduce a defined difference between observed and predicted values",
    importance: "it provides an explicit quantitative relationship that can be tested and interpreted",
    example: "estimating energy use from building size and outdoor temperature",
    components: ["outcome variable", "explanatory variables", "model form", "residuals"],
    related: ["statistics", "correlation", "model evaluation"],
  },
  {
    id: "data-clustering",
    term: "clustering",
    aliases: ["data grouping", "unsupervised grouping"],
    category: "data-science",
    definition: "the grouping of observations according to a defined measure of similarity without supplied class labels",
    purpose: "reveal structure or segments in unlabelled data",
    mechanism: "an algorithm assigns or links observations so within-group similarity is favored over between-group similarity",
    importance: "unlabelled collections can contain useful organization that is not known in advance",
    example: "grouping customers by similar purchasing patterns",
    components: ["observations", "features", "similarity measure", "grouping rule"],
    related: ["classification", "data visualization", "machine learning"],
  },
  {
    id: "data-probability-distribution",
    term: "probability distribution",
    aliases: ["probability model", "distribution of outcomes"],
    category: "mathematics",
    definition: "a rule that assigns probabilities to the possible values of a random quantity",
    purpose: "describe uncertainty in a form that supports calculation",
    mechanism: "probability mass or density is allocated across outcomes while satisfying normalization rules",
    importance: "uncertain measurements and predictions require more information than a single expected value",
    example: "a bell-shaped normal distribution describing repeated measurement error",
    components: ["outcome space", "probabilities or density", "parameters", "summary measures"],
    related: ["probability", "statistics", "confidence interval"],
  },
  {
    id: "data-statistical-significance",
    term: "statistical significance",
    aliases: ["significance test result", "statistically significant result"],
    category: "data-science",
    definition: "a test conclusion that observed data would be sufficiently unusual under a specified null model",
    purpose: "apply a predeclared evidence threshold in hypothesis testing",
    mechanism: "a test statistic is converted to a probability under the null model and compared with a chosen threshold",
    importance: "it standardizes one evidential decision but does not measure practical importance or prove a claim",
    example: "a study comparing a p-value with a preselected significance level",
    components: ["null hypothesis", "test statistic", "p-value", "significance level"],
    related: ["hypothesis testing", "confidence interval", "statistics"],
  },
  {
    id: "data-confidence-interval",
    term: "confidence interval",
    aliases: ["interval estimate", "statistical confidence range"],
    category: "data-science",
    definition: "an interval produced by a method designed to contain an unknown parameter at a stated long-run rate",
    purpose: "express estimation uncertainty around a sample-based value",
    mechanism: "sample information and an assumed sampling model determine a range around an estimate",
    importance: "a point estimate alone hides how much it could vary across samples",
    example: "reporting an estimated mean together with a 95 percent confidence interval",
    components: ["point estimate", "standard error", "confidence level", "interval bounds"],
    related: ["statistics", "hypothesis testing", "probability distribution"],
  },
  {
    id: "data-visualization",
    term: "data visualization",
    aliases: ["visual data display", "statistical graphics"],
    category: "data-science",
    definition: "the visual encoding of data values and relationships into graphical marks",
    purpose: "make patterns, comparisons, and exceptions easier to inspect",
    mechanism: "dimensions and measures are mapped to position, length, color, shape, or other visible properties",
    importance: "well-chosen visual encodings can reveal structure that is difficult to find in raw tables",
    example: "a line chart showing temperature across time",
    components: ["data", "visual marks", "encodings", "scales and labels"],
    related: ["statistics", "measurement", "communication"],
  },
  {
    id: "data-pipeline",
    term: "data pipeline",
    aliases: ["data processing pipeline", "data flow system"],
    category: "data-science",
    definition: "an ordered system that moves and transforms data between sources and destinations",
    purpose: "make repeated data collection and preparation reliable",
    mechanism: "stages extract, validate, transform, store, and monitor records according to defined contracts",
    importance: "analysis is unreliable when data movement and transformation cannot be reproduced",
    example: "collecting transaction records nightly and loading cleaned totals into a warehouse",
    components: ["sources", "transformations", "storage", "monitoring"],
    related: ["a database", "data governance", "a distributed system"],
  },
  {
    id: "data-governance",
    term: "data governance",
    aliases: ["information governance", "data management policy"],
    category: "data-science",
    definition: "the system of responsibilities and rules used to manage data quality, access, meaning, and use",
    purpose: "keep important data controlled, interpretable, and accountable",
    mechanism: "owners define standards, permissions, definitions, retention, and review processes",
    importance: "shared data causes errors when its meaning, quality, and authority are unclear",
    example: "assigning an owner and definition to a company's customer-count metric",
    components: ["ownership", "standards", "access control", "quality review"],
    related: ["data pipeline", "cybersecurity", "quality assurance"],
  },
  {
    id: "data-bias-variance",
    term: "bias-variance tradeoff",
    aliases: ["model bias and variance", "underfit-overfit balance"],
    category: "data-science",
    definition: "the tension between error from overly rigid assumptions and error from sensitivity to training samples",
    purpose: "reason about whether a fitted model is too simple or too dependent on its examples",
    mechanism: "model flexibility can reduce systematic error while increasing variation across possible training sets",
    importance: "good training performance alone does not guarantee reliable behavior on new data",
    example: "a very deep decision tree fitting noise that a simpler tree ignores",
    components: ["model flexibility", "bias", "variance", "generalization error"],
    related: ["machine learning", "model evaluation", "training data"],
  },
  {
    id: "data-model-evaluation",
    term: "model evaluation",
    aliases: ["predictive model assessment", "model performance testing"],
    category: "data-science",
    definition: "the structured measurement of how a model behaves on relevant data and conditions",
    purpose: "determine whether a model is accurate, useful, robust, and appropriate for its intended task",
    mechanism: "predefined metrics are calculated on held-out or specially designed test cases",
    importance: "a model cannot be trusted merely because it fitted its training examples",
    example: "measuring precision and recall on messages excluded from classifier training",
    components: ["evaluation dataset", "metrics", "baselines", "error analysis"],
    related: ["software testing", "machine learning", "training data"],
  },

  // Biology, medicine, and public health: 20 topics.
  {
    id: "bio-gene",
    term: "gene",
    aliases: ["genetic unit", "DNA gene"],
    category: "medicine",
    definition: "a region of genetic material that contributes to a functional product or regulated biological role",
    purpose: "carry inheritable instructions used in cellular processes",
    mechanism: "cellular machinery reads regulated DNA sequences to produce RNA and often protein",
    importance: "genes connect inherited information with biological structure and function",
    example: "a gene providing instructions used to produce a particular enzyme",
    components: ["regulatory regions", "transcribed sequence", "DNA bases", "functional product"],
    related: ["DNA", "protein", "evolution"],
  },
  {
    id: "bio-protein",
    term: "protein",
    aliases: ["biological protein", "amino-acid polymer"],
    category: "medicine",
    definition: "a folded biological molecule made from one or more chains of amino acids",
    purpose: "perform structural, chemical, signaling, transport, and regulatory work in organisms",
    mechanism: "an amino-acid sequence folds into a shape whose physical properties support a function",
    importance: "most cellular processes depend directly on protein structure and interaction",
    example: "hemoglobin carrying oxygen in blood",
    components: ["amino acids", "polypeptide chain", "folded structure", "functional sites"],
    related: ["gene", "enzyme", "a cell"],
  },
  {
    id: "bio-enzyme",
    term: "enzyme",
    aliases: ["biological catalyst", "catalytic protein"],
    category: "medicine",
    definition: "a biological catalyst that increases the rate of a chemical reaction without being consumed by it",
    purpose: "make necessary biochemical reactions occur quickly under cellular conditions",
    mechanism: "a specific active site binds reactants and lowers the reaction's activation barrier",
    importance: "life depends on controlled reaction rates that would otherwise be too slow",
    example: "lactase helping break lactose into smaller sugars",
    components: ["active site", "substrate", "catalytic groups", "product"],
    related: ["protein", "metabolism", "chemistry"],
  },
  {
    id: "bio-metabolism",
    term: "metabolism",
    aliases: ["cellular metabolism", "biochemical processing"],
    category: "medicine",
    definition: "the connected set of chemical reactions that transforms matter and energy in an organism",
    purpose: "maintain cells, build biological material, and obtain usable energy",
    mechanism: "enzyme-controlled pathways break down some molecules and construct others",
    importance: "organisms must continually balance energy use, repair, and material production",
    example: "cells converting glucose through linked reactions into usable chemical energy",
    components: ["catabolic pathways", "anabolic pathways", "enzymes", "energy carriers"],
    related: ["enzyme", "nutrition", "homeostasis"],
  },
  {
    id: "bio-neuron",
    term: "neuron",
    aliases: ["nerve cell", "neural cell"],
    category: "medicine",
    definition: "a specialized cell that receives, processes, and transmits electrochemical signals",
    purpose: "carry information through nervous systems",
    mechanism: "changes in membrane voltage travel along the cell and trigger chemical or electrical signaling to other cells",
    importance: "sensation, movement, learning, and coordination require rapid communication between cells",
    example: "a motor neuron transmitting a signal that contributes to muscle contraction",
    components: ["cell body", "dendrites", "axon", "synapses"],
    related: ["nervous system", "a cell", "electricity"],
  },
  {
    id: "bio-immune-system",
    term: "immune system",
    aliases: ["body defense system", "immune defenses"],
    category: "medicine",
    definition: "the coordinated cells, tissues, and molecules that detect and respond to biological threats",
    purpose: "limit harmful pathogens and remove damaged or abnormal material",
    mechanism: "barriers and innate responses act first, while adaptive cells can form targeted responses and memory",
    importance: "organisms need defense that distinguishes threats from their own functioning tissues",
    example: "immune cells recognizing a viral marker and producing a targeted response",
    components: ["barriers", "innate immunity", "adaptive immunity", "immune memory"],
    related: ["vaccine", "pathogen", "public health"],
  },
  {
    id: "bio-vaccine",
    term: "vaccine",
    aliases: ["immunization vaccine", "preventive immune preparation"],
    category: "medicine",
    definition: "a biological preparation designed to train immune recognition of a particular threat",
    purpose: "reduce the likelihood or severity of a future infectious disease",
    mechanism: "an antigen or encoded antigen safely prompts an adaptive immune response and memory",
    importance: "prepared immune memory can respond faster than a first encounter with a pathogen",
    example: "a vaccine presenting a harmless target associated with a virus",
    components: ["target antigen", "delivery method", "formulation", "immune response"],
    related: ["immune system", "pathogen", "epidemiology"],
  },
  {
    id: "bio-pathogen",
    term: "pathogen",
    aliases: ["disease-causing agent", "infectious agent"],
    category: "medicine",
    definition: "a biological agent capable of causing disease in a host",
    purpose: "the term classifies disease-causing organisms or particles for study and control",
    mechanism: "a pathogen enters or affects a host, reproduces or acts, and disrupts normal biological function",
    importance: "different agents spread and cause harm through different mechanisms",
    example: "a bacterium causing disease after entering susceptible tissue",
    components: ["agent", "host", "transmission route", "disease mechanism"],
    related: ["immune system", "epidemiology", "public health"],
  },
  {
    id: "bio-homeostasis",
    term: "homeostasis",
    aliases: ["biological regulation", "internal balance"],
    category: "medicine",
    definition: "the regulation of internal biological conditions within ranges compatible with function",
    purpose: "keep variables such as temperature, acidity, and glucose from drifting too far",
    mechanism: "sensors, control signals, and effectors form feedback loops that oppose or manage change",
    importance: "cellular processes work only within limited physical and chemical conditions",
    example: "sweating helping reduce body temperature when it rises",
    components: ["regulated variable", "sensor", "control center", "effector"],
    related: ["a control system", "metabolism", "hormone"],
  },
  {
    id: "bio-clinical-trial",
    term: "clinical trial",
    aliases: ["human intervention study", "clinical research trial"],
    category: "medicine",
    definition: "a planned study in people that evaluates a health-related intervention under a defined protocol",
    purpose: "measure benefits, harms, dosage, or comparative performance using systematically collected evidence",
    mechanism: "eligible participants follow assigned procedures while outcomes and adverse events are recorded",
    importance: "treatments require controlled evidence beyond laboratory theory or individual anecdotes",
    example: "randomly assigning participants to compare a new therapy with standard care",
    components: ["protocol", "participants", "intervention and comparison", "outcomes"],
    related: ["hypothesis testing", "epidemiology", "treatment"],
  },
  {
    id: "bio-epidemiology",
    term: "epidemiology",
    aliases: ["population disease study", "health distribution science"],
    category: "medicine",
    definition: "the study of the distribution and determinants of health events in populations",
    purpose: "identify patterns, causes, and control opportunities for population health",
    mechanism: "researchers compare measured exposures and outcomes across people, places, and time",
    importance: "individual cases alone cannot reveal how risk and disease are distributed",
    example: "estimating whether an infection rate differs between exposed and unexposed groups",
    components: ["population", "exposure", "outcome", "study design"],
    related: ["public health", "statistics", "a clinical trial"],
  },
  {
    id: "bio-public-health",
    term: "public health",
    aliases: ["population health practice", "community health protection"],
    category: "medicine",
    definition: "the organized effort to protect and improve health across populations",
    purpose: "prevent harm and create conditions that support health at community scale",
    mechanism: "surveillance, policy, education, environmental action, and services address shared risks",
    importance: "many health outcomes depend on systems and environments beyond individual treatment",
    example: "monitoring drinking-water quality across a city",
    components: ["surveillance", "prevention", "policy", "community services"],
    related: ["epidemiology", "health", "risk management"],
  },
  {
    id: "bio-diagnosis",
    term: "diagnosis",
    aliases: ["clinical identification", "medical diagnosis"],
    category: "medicine",
    definition: "the reasoned identification or classification of a condition from available evidence",
    purpose: "organize symptoms, history, examinations, and tests into a supported clinical conclusion",
    mechanism: "possible explanations are compared with findings and revised as evidence is gathered",
    importance: "different conditions can produce similar signs but require different responses",
    example: "a clinician combining history, examination, and laboratory results to identify a condition",
    components: ["history", "findings", "differential possibilities", "supporting tests"],
    related: ["treatment", "logical inference", "health"],
  },
  {
    id: "bio-treatment",
    term: "treatment",
    aliases: ["clinical treatment", "therapeutic intervention"],
    category: "medicine",
    definition: "an intervention intended to improve, control, or manage a health condition",
    purpose: "change symptoms, causes, risks, or functional effects according to clinical goals",
    mechanism: "a selected therapy acts through biological, behavioral, physical, or supportive pathways",
    importance: "effective care requires matching an intervention to evidence, condition, and patient circumstances",
    example: "using a prescribed medicine and follow-up monitoring for a diagnosed condition",
    components: ["clinical goal", "intervention", "monitoring", "risk-benefit review"],
    related: ["diagnosis", "a clinical trial", "pharmacology"],
  },
  {
    id: "bio-pharmacology",
    term: "pharmacology",
    aliases: ["drug action science", "medicine pharmacology"],
    category: "medicine",
    definition: "the study of how drugs interact with biological systems",
    purpose: "understand therapeutic effects, movement through the body, dosing, and adverse effects",
    mechanism: "research examines drug targets, concentration over time, biological response, and elimination",
    importance: "a useful drug must reach an effective exposure without unacceptable harm",
    example: "measuring how quickly a medicine is absorbed and cleared",
    components: ["drug target", "dose", "pharmacokinetics", "pharmacodynamics"],
    related: ["treatment", "chemistry", "metabolism"],
  },
  {
    id: "bio-microbiome",
    term: "microbiome",
    aliases: ["microbial community", "host-associated microbes"],
    category: "medicine",
    definition: "the community of microorganisms and their collective genetic material in a particular environment",
    purpose: "describe how microbial populations interact with one another and their surroundings",
    mechanism: "many microbial species exchange resources and signals while responding to environmental conditions",
    importance: "microbial communities can affect ecosystems, digestion, immunity, and disease processes",
    example: "the diverse microbial community living in the human intestine",
    components: ["microorganisms", "genes", "local environment", "interactions"],
    related: ["an ecosystem", "immune system", "metabolism"],
  },
  {
    id: "bio-hormone",
    term: "hormone",
    aliases: ["chemical messenger", "endocrine signal"],
    category: "medicine",
    definition: "a signaling molecule released in one location that regulates cells elsewhere in an organism",
    purpose: "coordinate processes such as growth, metabolism, reproduction, and stress response",
    mechanism: "the molecule travels to target cells and binds receptors that change cellular activity",
    importance: "distant tissues need coordinated control across changing internal conditions",
    example: "insulin signaling cells to respond to rising blood glucose",
    components: ["source tissue", "signal molecule", "receptor", "target response"],
    related: ["homeostasis", "metabolism", "a cell"],
  },
  {
    id: "bio-tissue",
    term: "tissue",
    aliases: ["biological tissue", "organized cell group"],
    category: "medicine",
    definition: "an organized group of cells and surrounding material that performs related functions",
    purpose: "combine specialized cells into a functional biological structure",
    mechanism: "cells adhere, communicate, and interact with extracellular material in a repeated organization",
    importance: "multicellular organisms depend on levels of organization above individual cells",
    example: "muscle tissue producing force through coordinated cell contraction",
    components: ["cells", "extracellular material", "organization", "shared function"],
    related: ["a cell", "organ", "biology"],
  },
  {
    id: "bio-organ",
    term: "organ",
    aliases: ["body organ", "biological organ"],
    category: "medicine",
    definition: "a body structure made of multiple tissues that performs coordinated functions",
    purpose: "combine specialized tissue roles into larger physiological tasks",
    mechanism: "different tissues exchange material, forces, and signals within one organized structure",
    importance: "complex organism functions require coordinated structures beyond a single tissue",
    example: "the heart combining muscle, connective, nervous, and vascular tissues to pump blood",
    components: ["multiple tissues", "blood or material supply", "control signals", "functional structure"],
    related: ["tissue", "nervous system", "homeostasis"],
  },
  {
    id: "bio-nervous-system",
    term: "nervous system",
    aliases: ["neural system", "body communication network"],
    category: "medicine",
    definition: "the biological network that senses conditions, processes information, and coordinates rapid responses",
    purpose: "connect perception, control, movement, and internal regulation",
    mechanism: "neurons and supporting cells transmit electrical and chemical signals through organized pathways",
    importance: "fast body-wide coordination is necessary for behavior and survival",
    example: "sensory signals reaching the spinal cord and contributing to a rapid withdrawal response",
    components: ["brain", "spinal cord", "peripheral nerves", "sensory receptors"],
    related: ["neuron", "psychology", "a control system"],
  },

  // Quantitative reasoning and mathematical tools: 15 topics.
  {
    id: "math-linear-algebra",
    term: "linear algebra",
    aliases: ["vector and matrix algebra", "linear mathematics"],
    category: "mathematics",
    definition: "the branch of mathematics concerned with vectors, matrices, linear mappings, and systems of linear equations",
    purpose: "represent and solve relationships that preserve addition and scalar multiplication",
    mechanism: "coordinates and matrices encode transformations and simultaneous linear constraints",
    importance: "many scientific and computing problems can be expressed as structured operations on vectors",
    example: "solving several linear equations by reducing a matrix",
    components: ["vectors", "matrices", "linear transformations", "vector spaces"],
    related: ["vector", "matrix", "machine learning"],
  },
  {
    id: "math-derivative",
    term: "derivative",
    aliases: ["rate-of-change derivative", "differential derivative"],
    category: "mathematics",
    definition: "a value describing the instantaneous rate at which one quantity changes with another",
    purpose: "measure local change and slope",
    mechanism: "a limit compares increasingly small changes in output with corresponding changes in input",
    importance: "rates of change support prediction, optimization, and physical modeling",
    example: "velocity as the derivative of position with respect to time",
    components: ["function", "input change", "output change", "limit"],
    related: ["calculus", "integral", "optimization"],
  },
  {
    id: "math-integral",
    term: "integral",
    aliases: ["calculus integral", "continuous accumulation"],
    category: "mathematics",
    definition: "a mathematical quantity representing continuous accumulation over an interval or region",
    purpose: "combine infinitely many small contributions into a total",
    mechanism: "a limit of sums approaches the accumulated value as partitions become finer",
    importance: "totals such as area, mass, probability, and distance often arise from continuous variation",
    example: "finding distance by integrating velocity across time",
    components: ["integrand", "domain", "differential element", "accumulated result"],
    related: ["calculus", "derivative", "measurement"],
  },
  {
    id: "math-vector",
    term: "vector",
    aliases: ["mathematical vector", "ordered numeric vector"],
    category: "mathematics",
    definition: "an ordered mathematical object whose components can represent magnitude across dimensions",
    purpose: "represent quantities with multiple coordinates or a magnitude and direction",
    mechanism: "component-wise operations and geometric rules define addition, scaling, length, and direction",
    importance: "many physical and computational states require more than one number",
    example: "a two-dimensional displacement represented by horizontal and vertical components",
    components: ["components", "dimension", "magnitude", "direction"],
    related: ["linear algebra", "matrix", "embedding"],
  },
  {
    id: "math-matrix",
    term: "matrix",
    aliases: ["number matrix", "rectangular numeric array"],
    category: "mathematics",
    definition: "a rectangular arrangement of values used to represent linear relationships or structured data",
    purpose: "organize coefficients and perform transformations on vectors or other matrices",
    mechanism: "indexed rows and columns combine through defined operations such as multiplication and inversion",
    importance: "matrices compactly encode systems, transformations, graphs, and data tables",
    example: "a rotation matrix transforming the coordinates of a vector",
    components: ["rows", "columns", "entries", "dimensions"],
    related: ["linear algebra", "vector", "data structure"],
  },
  {
    id: "math-graph-theory",
    term: "graph theory",
    aliases: ["network mathematics", "mathematics of graphs"],
    category: "mathematics",
    definition: "the study of objects represented as vertices connected by edges",
    purpose: "reason about pairwise relationships and network structure",
    mechanism: "properties are derived from adjacency, paths, cycles, connectivity, and edge direction or weight",
    importance: "transport, communication, dependency, and social systems naturally form networks",
    example: "finding the shortest path between cities connected by roads",
    components: ["vertices", "edges", "paths", "connectivity"],
    related: ["a computer network", "an algorithm", "combinatorics"],
  },
  {
    id: "math-combinatorics",
    term: "combinatorics",
    aliases: ["counting mathematics", "discrete arrangement study"],
    category: "mathematics",
    definition: "the study of counting, arranging, and selecting discrete objects",
    purpose: "determine how many configurations satisfy stated constraints",
    mechanism: "counting principles decompose possibilities into products, sums, permutations, or combinations",
    importance: "probability and discrete algorithms often depend on the size of a possibility space",
    example: "counting the ways to choose three people from a group",
    components: ["objects", "selection rules", "arrangements", "constraints"],
    related: ["probability", "graph theory", "an algorithm"],
  },
  {
    id: "math-optimization",
    term: "optimization",
    aliases: ["mathematical optimization", "objective optimization"],
    category: "mathematics",
    definition: "the process of finding an allowed solution that minimizes or maximizes a defined objective",
    purpose: "choose the best measured outcome under stated constraints",
    mechanism: "a search or mathematical method evaluates feasible candidates and improves the objective",
    importance: "resources, designs, and model parameters often require explicit trade-offs",
    example: "minimizing delivery distance while visiting every required location",
    components: ["decision variables", "objective", "constraints", "feasible solutions"],
    related: ["a decision", "an algorithm", "calculus"],
  },
  {
    id: "math-hypothesis-testing",
    term: "hypothesis testing",
    aliases: ["statistical hypothesis test", "null-hypothesis testing"],
    category: "data-science",
    definition: "a formal procedure for comparing observed data with a specified statistical claim",
    purpose: "make a controlled evidential decision while limiting a defined error rate",
    mechanism: "a statistic measures disagreement with a null hypothesis and is judged against a preselected rule",
    importance: "random variation can produce apparent differences even when a null model is adequate",
    example: "testing whether two sample means differ more than expected under a no-difference model",
    components: ["null hypothesis", "alternative", "test statistic", "decision rule"],
    related: ["statistical significance", "confidence interval", "statistics"],
  },
  {
    id: "math-correlation",
    term: "correlation",
    aliases: ["statistical association", "correlation coefficient"],
    category: "data-science",
    definition: "a measure of how two variables vary together according to a specified relationship",
    purpose: "summarize the direction and strength of an association",
    mechanism: "paired observations are compared with their respective variation around central values",
    importance: "association can guide investigation but does not by itself establish cause",
    example: "measuring whether higher temperature tends to occur with higher electricity use",
    components: ["paired variables", "observations", "association measure", "uncertainty"],
    related: ["causation", "regression analysis", "statistics"],
  },
  {
    id: "math-causation",
    term: "causation",
    aliases: ["causal relationship", "cause-and-effect relation"],
    category: "data-science",
    definition: "a relationship in which changing one factor contributes to changing an outcome",
    purpose: "distinguish effects of interventions from mere association",
    mechanism: "causal reasoning compares outcomes under alternative conditions while controlling competing explanations",
    importance: "decisions about action require knowing what would change an outcome, not only what accompanies it",
    example: "a randomized trial estimating the effect of an intervention",
    components: ["cause", "outcome", "counterfactual comparison", "confounding controls"],
    related: ["correlation", "a clinical trial", "logical inference"],
  },
  {
    id: "math-bayes-theorem",
    term: "Bayes theorem",
    aliases: ["Bayes rule", "Bayesian updating formula"],
    category: "mathematics",
    definition: "a probability rule that updates belief in a hypothesis using the likelihood of observed evidence",
    purpose: "combine prior probability with new evidence consistently",
    mechanism: "the probability of evidence under a hypothesis is weighted by the prior and normalized across alternatives",
    importance: "the meaning of evidence depends on both its likelihood and the starting prevalence of alternatives",
    example: "updating the probability of a condition after a test result",
    components: ["prior", "likelihood", "evidence probability", "posterior"],
    related: ["probability", "diagnosis", "logical inference"],
  },
  {
    id: "math-recursion",
    term: "recursion",
    aliases: ["recursive process", "self-referential computation"],
    category: "computing",
    definition: "a method in which a problem or definition refers to smaller instances of itself",
    purpose: "express repeated structure through a base case and a reduction rule",
    mechanism: "each call reduces the problem until a terminating case returns a result through earlier calls",
    importance: "hierarchies and divide-and-conquer problems often have naturally recursive structure",
    example: "computing a factorial by multiplying a number by the factorial of the preceding number",
    components: ["base case", "recursive case", "smaller input", "return path"],
    related: ["an algorithm", "programming", "data structure"],
  },
  {
    id: "math-computational-complexity",
    term: "computational complexity",
    aliases: ["algorithmic complexity", "resource growth analysis"],
    category: "computing",
    definition: "the study of how an algorithm's required resources grow with input size",
    purpose: "compare scalability independently of one particular machine",
    mechanism: "time or memory operations are bounded using functions of the input size",
    importance: "an algorithm that works on small inputs may become impractical as data grows",
    example: "describing a search that examines every item as linear time",
    components: ["input size", "resource measure", "growth function", "upper or lower bound"],
    related: ["an algorithm", "data structure", "optimization"],
  },
  {
    id: "math-logical-inference",
    term: "logical inference",
    aliases: ["deductive inference", "reasoned conclusion"],
    category: "humanities",
    definition: "the derivation of a conclusion from stated premises according to a rule of logic",
    purpose: "make the connection between assumptions and conclusions explicit",
    mechanism: "an inference rule preserves validity from a recognized premise form to a conclusion",
    importance: "a conclusion should be separated from the evidence and rule that support it",
    example: "inferring that an object has a property because all members of its class have that property",
    components: ["premises", "inference rule", "conclusion", "validity check"],
    related: ["critical thinking", "a logical fallacy", "a hypothesis"],
  },

  // Economics and business practice: 15 topics.
  {
    id: "biz-supply-demand",
    term: "supply and demand",
    aliases: ["market supply and demand", "supply-demand model"],
    category: "business",
    definition: "an economic model relating how much sellers offer and buyers seek at different prices",
    purpose: "explain how scarcity and willingness to trade influence market price and quantity",
    mechanism: "market pressure changes when planned supply and demand differ at a given price",
    importance: "prices and quantities often respond to shifts in costs, preferences, and available alternatives",
    example: "limited concert seats facing many willing buyers",
    components: ["supply curve", "demand curve", "price", "market quantity"],
    related: ["economics", "inflation", "market structure"],
  },
  {
    id: "biz-inflation",
    term: "inflation",
    aliases: ["general price inflation", "price-level increase"],
    category: "business",
    definition: "a sustained increase in the general level of prices across an economy",
    purpose: "describe how the purchasing power of money changes over time",
    mechanism: "price indexes compare the cost of a broad basket across periods",
    importance: "inflation affects wages, savings, borrowing, planning, and real purchasing power",
    example: "a consumer price index rising across many categories over a year",
    components: ["price index", "basket of goods", "time period", "rate of change"],
    related: ["money", "interest rate", "gross domestic product"],
  },
  {
    id: "biz-interest-rate",
    term: "interest rate",
    aliases: ["borrowing rate", "rate of interest"],
    category: "business",
    definition: "the price of borrowing money or the return paid for lending it, expressed relative to principal and time",
    purpose: "compensate for time, risk, and alternative uses of funds",
    mechanism: "interest accumulates according to the stated rate, principal, and compounding convention",
    importance: "rates influence borrowing, saving, investment, and asset values",
    example: "a loan charging annual interest on its outstanding balance",
    components: ["principal", "rate", "time period", "compounding rule"],
    related: ["money", "inflation", "cash flow"],
  },
  {
    id: "biz-gdp",
    term: "gross domestic product",
    aliases: ["GDP", "domestic economic output"],
    category: "business",
    definition: "the market value of final goods and services produced within an economy during a period",
    purpose: "summarize the scale and change of measured domestic production",
    mechanism: "statistical agencies aggregate production, expenditure, or income accounts under consistent definitions",
    importance: "it provides a broad output measure but does not capture every aspect of welfare or distribution",
    example: "adding household consumption, investment, government spending, and net exports",
    components: ["consumption", "investment", "government spending", "net exports"],
    related: ["economics", "inflation", "accounting"],
  },
  {
    id: "biz-opportunity-cost",
    term: "opportunity cost",
    aliases: ["next-best alternative cost", "forgone alternative value"],
    category: "business",
    definition: "the value of the best alternative given up when a choice is made",
    purpose: "include forgone options when comparing decisions",
    mechanism: "the chosen outcome is evaluated against the most valuable feasible alternative",
    importance: "resources used for one purpose cannot simultaneously produce every other possible benefit",
    example: "time spent on one project replacing time that could have been used on another",
    components: ["choice", "feasible alternatives", "best forgone option", "value criterion"],
    related: ["a decision", "economics", "optimization"],
  },
  {
    id: "biz-market-structure",
    term: "market structure",
    aliases: ["competitive market structure", "industry market form"],
    category: "business",
    definition: "the organization of a market according to seller concentration, product differences, entry conditions, and information",
    purpose: "analyze how competitive conditions influence pricing and behavior",
    mechanism: "the number and power of participants shape strategic choices and market outcomes",
    importance: "the same demand can produce different outcomes under different competitive arrangements",
    example: "comparing a market with many small sellers to one dominated by a few firms",
    components: ["number of firms", "entry barriers", "product differentiation", "market power"],
    related: ["supply and demand", "economics", "business model"],
  },
  {
    id: "biz-accounting",
    term: "accounting",
    aliases: ["financial accounting", "business record accounting"],
    category: "business",
    definition: "the systematic recording, classification, summarization, and interpretation of financial transactions",
    purpose: "produce consistent information about an organization's financial position and activity",
    mechanism: "transactions are recorded under defined recognition and measurement rules and assembled into statements",
    importance: "owners, managers, lenders, and regulators need traceable financial information",
    example: "recording a sale and its effect on revenue, cash, and inventory",
    components: ["transactions", "accounts", "ledgers", "financial statements"],
    related: ["balance sheet", "cash flow", "a budget"],
  },
  {
    id: "biz-balance-sheet",
    term: "balance sheet",
    aliases: ["statement of financial position", "financial position statement"],
    category: "business",
    definition: "a financial statement listing an entity's assets, liabilities, and equity at a point in time",
    purpose: "summarize what an entity controls and owes and the residual ownership claim",
    mechanism: "recorded balances are organized under the equation assets equal liabilities plus equity",
    importance: "the statement supports analysis of liquidity, leverage, and financial structure",
    example: "reporting cash, inventory, loans, and owner equity at year end",
    components: ["assets", "liabilities", "equity", "reporting date"],
    related: ["accounting", "cash flow", "risk management"],
  },
  {
    id: "biz-cash-flow",
    term: "cash flow",
    aliases: ["cash movement", "cash inflow and outflow"],
    category: "business",
    definition: "the movement of cash into and out of an activity or organization over time",
    purpose: "show whether liquid funds are available for obligations and operations",
    mechanism: "cash receipts and payments are classified and totaled by period",
    importance: "an organization can report profit while still lacking cash when payments occur at different times",
    example: "customers paying after expenses were already due",
    components: ["cash inflows", "cash outflows", "timing", "net cash change"],
    related: ["accounting", "a budget", "balance sheet"],
  },
  {
    id: "biz-project-management",
    term: "project management",
    aliases: ["project delivery management", "project coordination"],
    category: "business",
    definition: "the organized planning and coordination of temporary work intended to produce a defined outcome",
    purpose: "align scope, people, time, resources, and risks around a project goal",
    mechanism: "work is decomposed, assigned, scheduled, monitored, and adjusted against agreed constraints",
    importance: "complex temporary work fails when dependencies and decisions remain implicit",
    example: "coordinating design, engineering, testing, and launch for a product update",
    components: ["scope", "schedule", "resources", "risk and communication"],
    related: ["a plan", "teamwork", "risk management"],
  },
  {
    id: "biz-risk-management",
    term: "risk management",
    aliases: ["risk control process", "uncertainty management"],
    category: "business",
    definition: "the structured identification, assessment, treatment, and monitoring of uncertainty that could affect objectives",
    purpose: "reduce avoidable harm while making informed trade-offs",
    mechanism: "risks are described by cause, likelihood, impact, controls, and owners",
    importance: "uncertainty cannot be removed, but it can be made visible and managed",
    example: "preparing a backup supplier for a component with high disruption risk",
    components: ["risk identification", "likelihood and impact", "response", "monitoring"],
    related: ["a decision", "project management", "cybersecurity"],
  },
  {
    id: "biz-stakeholder",
    term: "stakeholder",
    aliases: ["interested party", "affected project party"],
    category: "business",
    definition: "a person or group that can affect, is affected by, or has a legitimate interest in an activity",
    purpose: "identify whose needs, authority, knowledge, or risks must be considered",
    mechanism: "stakeholders are mapped by interest, influence, impact, and required communication",
    importance: "decisions can fail when affected parties or decision owners are ignored",
    example: "customers, employees, suppliers, and regulators affected by a product change",
    components: ["interest", "influence", "impact", "engagement need"],
    related: ["project management", "communication", "leadership"],
  },
  {
    id: "biz-business-model",
    term: "business model",
    aliases: ["value creation model", "commercial operating model"],
    category: "business",
    definition: "a structured account of how an organization creates, delivers, and captures value",
    purpose: "connect customer needs, operations, resources, and financial logic",
    mechanism: "a value proposition is delivered through activities and partners while revenues and costs determine sustainability",
    importance: "a useful product does not automatically create a workable organization",
    example: "a subscription service funding ongoing access through recurring payments",
    components: ["value proposition", "customers", "operations", "revenue and cost structure"],
    related: ["market structure", "stakeholder", "cash flow"],
  },
  {
    id: "biz-supply-chain",
    term: "supply chain",
    aliases: ["production supply network", "goods supply network"],
    category: "business",
    definition: "the connected organizations and activities that move materials, information, and products from sources to users",
    purpose: "coordinate sourcing, production, storage, and delivery",
    mechanism: "orders and forecasts trigger flows through suppliers, facilities, transport, and inventory points",
    importance: "delays or failures at one stage can affect the entire product system",
    example: "components moving from suppliers to a factory and finished goods to retailers",
    components: ["suppliers", "production", "inventory", "distribution"],
    related: ["risk management", "project management", "quality assurance"],
  },
  {
    id: "biz-quality-assurance",
    term: "quality assurance",
    aliases: ["QA", "quality process assurance"],
    category: "business",
    definition: "the planned system used to provide confidence that processes and outputs meet defined quality requirements",
    purpose: "prevent defects and make quality repeatable",
    mechanism: "standards, reviews, tests, audits, and corrective actions are built into the work process",
    importance: "inspection at the end cannot reliably repair every upstream process problem",
    example: "requiring documented test evidence before a software release",
    components: ["quality criteria", "process controls", "verification", "corrective action"],
    related: ["software testing", "risk management", "measurement"],
  },

  // Law, research, and critical reasoning: 10 topics.
  {
    id: "law-constitution",
    term: "constitution",
    aliases: ["constitutional framework", "foundational legal charter"],
    category: "law",
    definition: "a foundational set of rules defining government powers, institutions, and protected principles",
    purpose: "establish how public authority is created, limited, and exercised",
    mechanism: "institutions interpret and apply higher-order rules to legislation and government action",
    importance: "public power requires a durable framework of authority and limits",
    example: "constitutional rules dividing powers among branches of government",
    components: ["institutional powers", "rights or principles", "amendment rules", "interpretation"],
    related: ["government", "democracy", "rule of law"],
  },
  {
    id: "law-rule-of-law",
    term: "rule of law",
    aliases: ["legal accountability principle", "law-governed authority"],
    category: "law",
    definition: "the principle that public and private power is exercised under known, applicable, and reviewable law",
    purpose: "limit arbitrary action and make legal consequences more predictable",
    mechanism: "laws are publicly established, institutions apply them, and decisions can be independently reviewed",
    importance: "rights and obligations have little force when authorities can disregard rules without accountability",
    example: "a court reviewing whether an official acted within legal authority",
    components: ["public laws", "equal application", "independent review", "procedural fairness"],
    related: ["law", "constitution", "democracy"],
  },
  {
    id: "law-contract",
    term: "contract",
    aliases: ["binding agreement", "legal agreement"],
    category: "law",
    definition: "an agreement that creates obligations recognized and enforceable under applicable law",
    purpose: "make exchanges and commitments sufficiently definite to rely upon",
    mechanism: "the parties express assent to terms while legal rules determine formation, interpretation, performance, and remedies",
    importance: "cooperation often depends on clear promises and consequences for nonperformance",
    example: "an agreement specifying a service, payment, timing, and responsibilities",
    components: ["parties", "terms", "agreement", "obligations and remedies"],
    related: ["law", "intellectual property", "a stakeholder"],
  },
  {
    id: "law-intellectual-property",
    term: "intellectual property",
    aliases: ["IP rights", "rights in creations"],
    category: "law",
    definition: "a group of legal rights concerning inventions, creative works, brands, and confidential knowledge",
    purpose: "define control and permitted use of certain intangible creations",
    mechanism: "different legal regimes grant limited rights according to subject matter and qualifying conditions",
    importance: "creative and technical work can be copied or used without transferring a physical object",
    example: "copyright governing reproduction of an original written work",
    components: ["copyright", "patent", "trademark", "trade secret"],
    related: ["law", "a contract", "creativity"],
  },
  {
    id: "human-ethics",
    term: "ethics",
    aliases: ["moral philosophy", "ethical reasoning"],
    category: "humanities",
    definition: "the systematic study of principles used to judge conduct, character, duties, and consequences",
    purpose: "make moral assumptions and trade-offs open to reasoned examination",
    mechanism: "cases and principles are compared through frameworks concerning outcomes, duties, virtues, rights, or relationships",
    importance: "decisions affecting others cannot be evaluated only by technical efficiency",
    example: "weighing privacy, benefit, consent, and fairness in a data project",
    components: ["values", "affected parties", "principles", "consequences"],
    related: ["philosophy", "critical thinking", "a decision"],
  },
  {
    id: "human-critical-thinking",
    term: "critical thinking",
    aliases: ["evidence-based reasoning", "careful analytical thinking"],
    category: "humanities",
    definition: "the disciplined evaluation of claims, evidence, assumptions, and reasoning",
    purpose: "reach conclusions that are proportionate to the available support",
    mechanism: "a thinker clarifies the question, checks sources, tests alternatives, and examines inference quality",
    importance: "confident language can hide weak evidence or invalid reasoning",
    example: "separating a measured correlation from a causal conclusion",
    components: ["claim", "evidence", "assumptions", "inference"],
    related: ["logical inference", "a logical fallacy", "the scientific method"],
  },
  {
    id: "human-rhetoric",
    term: "rhetoric",
    aliases: ["persuasive communication", "rhetorical practice"],
    category: "humanities",
    definition: "the study and practice of shaping communication for an audience and purpose",
    purpose: "make choices of argument, structure, language, and presentation deliberate",
    mechanism: "a communicator selects appeals, evidence, organization, and style suited to a context",
    importance: "how an argument is presented affects attention and interpretation independently of its truth",
    example: "adapting the same evidence for a technical report and a public speech",
    components: ["speaker or writer", "audience", "purpose", "message choices"],
    related: ["communication", "language", "critical thinking"],
  },
  {
    id: "research-primary-source",
    term: "primary source",
    aliases: ["firsthand source", "original evidence source"],
    category: "humanities",
    definition: "evidence created by a participant, observer, instrument, or process close to the event or subject studied",
    purpose: "provide direct material for analysis rather than only later interpretation",
    mechanism: "researchers examine the source's origin, context, content, limitations, and relation to other evidence",
    importance: "direct evidence still requires evaluation of perspective, authenticity, and representativeness",
    example: "a dated letter written by a participant in a historical event",
    components: ["creator", "time and context", "content", "provenance"],
    related: ["history", "peer review", "critical thinking"],
  },
  {
    id: "research-peer-review",
    term: "peer review",
    aliases: ["scholarly peer review", "expert manuscript review"],
    category: "humanities",
    definition: "the evaluation of scholarly work by other qualified people in the field before or after publication",
    purpose: "identify weaknesses in methods, reasoning, evidence, and presentation",
    mechanism: "reviewers examine a submission and recommend revision, acceptance, or rejection under editorial rules",
    importance: "independent scrutiny can improve work, although review does not guarantee correctness",
    example: "researchers reviewing a study's design and analysis before journal publication",
    components: ["submission", "reviewers", "evaluation criteria", "editorial decision"],
    related: ["the scientific method", "a primary source", "quality assurance"],
  },
  {
    id: "reason-logical-fallacy",
    term: "logical fallacy",
    aliases: ["reasoning fallacy", "argument error pattern"],
    category: "humanities",
    definition: "a recurring pattern of reasoning that fails to support its conclusion as claimed",
    purpose: "name and detect common ways arguments can go wrong",
    mechanism: "the premise-conclusion link is tested for relevance, sufficiency, consistency, and valid form",
    importance: "a persuasive conclusion can still rest on an invalid or inadequate inference",
    example: "rejecting a claim solely because of who stated it rather than evaluating its evidence",
    components: ["premises", "claimed conclusion", "inference pattern", "reasoning defect"],
    related: ["critical thinking", "logical inference", "rhetoric"],
  },
];

export const dv6TechnicalTopics = compileTechnicalTopics(seeds);
