import type { KnowledgeTopic } from "../types";

export const everydayWorldTopics: KnowledgeTopic[] = [
  {
    id: "time",
    term: "time",
    aliases: ["the concept of time", "temporal order"],
    category: "everyday",
    definition: "the dimension used to order events and measure duration",
    purpose: "describe when events occur and how long processes take",
    mechanism: "events are compared against recurring standards such as seconds, days, and years",
    importance: "shared time measurement coordinates activity and makes change comparable",
    example: "measuring a journey as lasting thirty minutes",
    components: ["sequence", "duration", "units", "reference points"],
    related: ["change", "clocks", "calendars", "motion"],
  },
  {
    id: "money",
    term: "money",
    aliases: ["currency", "medium of exchange"],
    category: "everyday",
    definition: "a socially accepted medium for exchange, valuation, and storing purchasing power",
    purpose: "make trade and accounting easier than direct barter",
    mechanism: "people and institutions accept standardized units in exchange for goods, services, or obligations",
    importance: "money provides a common scale for prices and enables exchange across time and distance",
    example: "using currency to buy food rather than directly trading another product",
    components: ["unit of account", "medium of exchange", "store of value"],
    related: ["prices", "banks", "economics", "budgets"],
  },
  {
    id: "budget",
    term: "a budget",
    aliases: ["budget", "spending plan", "financial budget"],
    category: "everyday",
    definition: "a plan that assigns expected income or resources to expenses and goals",
    purpose: "keep spending within limits and make priorities explicit",
    mechanism: "income and costs are grouped, estimated, compared, and revised over a period",
    importance: "a budget reveals tradeoffs before money is committed",
    example: "setting monthly limits for housing, food, transport, and savings",
    components: ["income", "fixed costs", "variable costs", "savings", "review"],
    related: ["money", "planning", "expenses", "saving"],
  },
  {
    id: "health",
    term: "health",
    aliases: ["human health", "wellness"],
    category: "everyday",
    definition: "a person's physical, mental, and social state of functioning and well-being",
    purpose: "support daily function, resilience, and quality of life",
    mechanism: "biology, behavior, environment, care, and social conditions interact over time",
    importance: "health affects a person's capacity to learn, work, relate, and recover",
    example: "balancing sleep, movement, nutrition, preventive care, and social support",
    components: ["physical health", "mental health", "social well-being", "environment"],
    related: ["exercise", "sleep", "nutrition", "medicine"],
  },
  {
    id: "exercise",
    term: "exercise",
    aliases: ["physical exercise", "physical activity"],
    category: "everyday",
    definition: "planned or purposeful physical activity performed to develop or maintain capability",
    purpose: "improve strength, endurance, mobility, skill, or health",
    mechanism: "repeated physical demand prompts the body to adapt during recovery",
    importance: "appropriate regular activity supports cardiovascular, muscular, metabolic, and mental health",
    example: "walking briskly for a sustained period several times a week",
    components: ["activity", "intensity", "duration", "recovery"],
    related: ["health", "fitness", "movement", "recovery"],
  },
  {
    id: "sleep",
    term: "sleep",
    aliases: ["human sleep", "restful sleep"],
    category: "everyday",
    definition: "a recurring biological state with reduced responsiveness and organized cycles of brain and body activity",
    purpose: "support restoration, memory, regulation, and normal functioning",
    mechanism: "circadian timing and accumulated sleep pressure coordinate repeating sleep stages",
    importance: "adequate sleep supports attention, mood, learning, immunity, and physical recovery",
    example: "maintaining a consistent sleep period in a dark and quiet environment",
    components: ["circadian rhythm", "sleep pressure", "sleep stages", "awakening"],
    related: ["health", "memory", "recovery", "habits"],
  },
  {
    id: "nutrition",
    term: "nutrition",
    aliases: ["human nutrition", "nourishment"],
    category: "everyday",
    definition: "the intake and use of substances needed for energy, growth, repair, and regulation",
    purpose: "supply the body with energy, building materials, and essential nutrients",
    mechanism: "food is digested, absorbed, transported, transformed, and used by cells",
    importance: "nutrition affects development, function, recovery, and long-term health",
    example: "eating a varied diet that supplies protein, fiber, vitamins, minerals, and energy",
    components: ["macronutrients", "micronutrients", "water", "digestion"],
    related: ["food", "health", "metabolism", "diet"],
  },
  {
    id: "habit",
    term: "a habit",
    aliases: ["habit", "habits", "habitual behavior"],
    category: "everyday",
    definition: "a behavior made easier or more automatic through repetition in a recurring context",
    purpose: "reduce the effort needed to repeat useful actions",
    mechanism: "a cue repeatedly triggers a routine that is reinforced by an immediate or expected result",
    importance: "small repeated behaviors can accumulate into large long-term effects",
    example: "placing a book beside the bed as a cue to read each evening",
    components: ["cue", "routine", "result", "repetition"],
    related: ["behavior", "goals", "practice", "routine"],
  },
  {
    id: "goal",
    term: "a goal",
    aliases: ["goal", "goals", "objective"],
    category: "everyday",
    definition: "a defined outcome toward which effort is directed",
    purpose: "give decisions and actions a target",
    mechanism: "a desired result is translated into criteria, milestones, and next actions",
    importance: "clear goals make progress and tradeoffs easier to evaluate",
    example: "finishing a first draft by Friday with a daily writing milestone",
    components: ["outcome", "criteria", "deadline", "actions"],
    related: ["planning", "motivation", "measurement", "habits"],
  },
  {
    id: "plan",
    term: "a plan",
    aliases: ["plan", "plans", "action plan"],
    category: "everyday",
    definition: "an ordered proposal for moving from a current state toward an intended result",
    purpose: "coordinate actions, resources, dependencies, and timing",
    mechanism: "the goal is divided into tasks with owners, order, constraints, and checkpoints",
    importance: "planning exposes missing steps and risks before they become costly",
    example: "listing the research, drafting, review, and delivery stages of a report",
    components: ["goal", "tasks", "sequence", "resources", "review"],
    related: ["goals", "decisions", "projects", "schedules"],
  },
  {
    id: "decision",
    term: "a decision",
    aliases: ["decision", "choice", "making a decision"],
    category: "everyday",
    definition: "the selection of an action or option from alternatives",
    purpose: "commit attention and resources under stated values and constraints",
    mechanism: "options are compared against criteria, evidence, uncertainty, and consequences",
    importance: "a consistent decision process reduces hidden tradeoffs and changing standards",
    example: "choosing transport by comparing time, cost, reliability, and accessibility",
    components: ["options", "criteria", "evidence", "tradeoffs"],
    related: ["planning", "risk", "goals", "problem solving"],
  },
  {
    id: "problem-solving",
    term: "problem solving",
    aliases: ["problem-solving", "solving problems", "solution process"],
    category: "everyday",
    definition: "the structured effort to move from an unsatisfactory condition to a workable result",
    purpose: "identify causes, constraints, and actions that resolve a defined problem",
    mechanism: "the problem is framed, evidence is gathered, options are tested, and results are checked",
    importance: "a process prevents premature solutions to the wrong problem",
    example: "isolating which change caused a program to fail before editing its code",
    components: ["problem frame", "causes", "options", "test", "evaluation"],
    related: ["decisions", "logic", "planning", "debugging"],
  },
  {
    id: "teamwork",
    term: "teamwork",
    aliases: ["team work", "working as a team", "collaboration"],
    category: "everyday",
    definition: "coordinated effort by people who share an outcome",
    purpose: "combine different skills, information, and capacity",
    mechanism: "roles, communication, dependencies, and feedback align individual contributions",
    importance: "good teamwork can solve problems too large or varied for one person",
    example: "a designer, engineer, and reviewer coordinating a product release",
    components: ["shared goal", "roles", "communication", "trust", "review"],
    related: ["communication", "leadership", "planning", "cooperation"],
  },
  {
    id: "leadership",
    term: "leadership",
    aliases: ["leading a team", "team leadership"],
    category: "everyday",
    definition: "the practice of helping a group establish direction and coordinate action",
    purpose: "align people, decisions, resources, and accountability around a shared outcome",
    mechanism: "leaders clarify priorities, distribute authority, remove obstacles, and model expected behavior",
    importance: "leadership shapes whether a group can act coherently under uncertainty",
    example: "making ownership clear while inviting evidence that could change a plan",
    components: ["direction", "communication", "delegation", "accountability"],
    related: ["teamwork", "decisions", "communication", "management"],
  },
  {
    id: "learning",
    term: "learning",
    aliases: ["human learning", "the learning process"],
    category: "everyday",
    definition: "a relatively durable change in knowledge or capability produced through experience and practice",
    purpose: "build understanding and improve future performance",
    mechanism: "attention, retrieval, feedback, correction, and repeated application strengthen usable memory",
    importance: "learning lets people adapt rather than repeat only inherited behavior",
    example: "solving varied practice problems and correcting mistakes",
    components: ["attention", "practice", "feedback", "memory", "transfer"],
    related: ["education", "memory", "practice", "knowledge"],
  },
  {
    id: "memory",
    term: "memory",
    aliases: ["human memory", "remembering"],
    category: "everyday",
    definition: "the set of processes by which information is encoded, retained, and later retrieved",
    purpose: "preserve useful effects of past experience",
    mechanism: "attention and meaning influence encoding, while cues and reconstruction influence retrieval",
    importance: "memory supports identity, learning, planning, language, and skilled action",
    example: "recalling a concept more reliably after spaced retrieval practice",
    components: ["encoding", "storage", "retrieval", "working memory"],
    related: ["learning", "attention", "sleep", "knowledge"],
  },
  {
    id: "creativity",
    term: "creativity",
    aliases: ["creative thinking", "creative work"],
    category: "everyday",
    definition: "the production of ideas or forms that are both novel in context and useful or meaningful",
    purpose: "develop possibilities beyond routine solutions",
    mechanism: "knowledge is recombined, constraints are reframed, variations are generated, and candidates are evaluated",
    importance: "creativity supports invention, art, adaptation, and problem solving",
    example: "repurposing an existing material to solve a new design constraint",
    components: ["knowledge", "variation", "novelty", "evaluation"],
    related: ["imagination", "art", "problem solving", "design"],
  },
  {
    id: "weather",
    term: "weather",
    aliases: ["daily weather", "atmospheric weather"],
    category: "world",
    definition: "the short-term state of the atmosphere at a place and time",
    purpose: "describe current conditions such as temperature, wind, cloud, and precipitation",
    mechanism: "uneven heating, pressure differences, moisture, and air movement interact across the atmosphere",
    importance: "weather affects safety, transport, agriculture, energy use, and daily planning",
    example: "a cold front producing falling temperature, cloud, and rain",
    components: ["temperature", "pressure", "wind", "humidity", "precipitation"],
    related: ["climate", "atmosphere", "storms", "forecasting"],
  },
  {
    id: "climate",
    term: "climate",
    aliases: ["long-term climate", "climate system"],
    category: "world",
    definition: "the long-term statistical pattern of weather and related environmental conditions",
    purpose: "describe typical conditions, ranges, and trends over extended periods",
    mechanism: "energy from the Sun interacts with the atmosphere, oceans, land, ice, and living systems",
    importance: "climate shapes ecosystems, water, agriculture, infrastructure, and long-term risk",
    example: "describing a region by decades of temperature and rainfall records",
    components: ["atmosphere", "oceans", "land", "ice", "energy balance"],
    related: ["weather", "atmosphere", "oceans", "environment"],
  },
  {
    id: "water-cycle",
    term: "the water cycle",
    aliases: ["water cycle", "hydrologic cycle"],
    category: "world",
    definition: "the continuous movement of water among the atmosphere, land, oceans, and living systems",
    purpose: "circulate and redistribute Earth's water",
    mechanism: "evaporation, condensation, precipitation, infiltration, runoff, and biological transport move water",
    importance: "the water cycle supplies freshwater and links weather, climate, landscapes, and life",
    example: "ocean water evaporating, forming clouds, and returning as rain",
    components: ["evaporation", "condensation", "precipitation", "runoff"],
    related: ["weather", "oceans", "rivers", "climate"],
  },
  {
    id: "biodiversity",
    term: "biodiversity",
    aliases: ["biological diversity", "diversity of life"],
    category: "world",
    definition: "variation among living organisms at genetic, species, and ecosystem levels",
    purpose: "describe the variety and distribution of life",
    mechanism: "evolution, migration, environmental differences, and ecological interactions generate and maintain variation",
    importance: "biodiversity supports resilient ecosystems and a wide range of ecological functions",
    example: "a forest containing many genes, species, and habitat types",
    components: ["genetic diversity", "species diversity", "ecosystem diversity"],
    related: ["ecology", "evolution", "ecosystems", "conservation"],
  },
  {
    id: "pollution",
    term: "pollution",
    aliases: ["environmental pollution", "contamination"],
    category: "world",
    definition: "the introduction of substances or energy that causes harmful environmental change",
    purpose: "name and measure damaging contamination so it can be prevented or reduced",
    mechanism: "emissions or waste enter air, water, soil, food webs, or sensory environments faster than systems can safely process them",
    importance: "pollution can damage health, ecosystems, materials, and climate",
    example: "fine particles from combustion accumulating in urban air",
    components: ["source", "pollutant", "pathway", "exposure", "effect"],
    related: ["environment", "waste", "health", "conservation"],
  },
  {
    id: "recycling",
    term: "recycling",
    aliases: ["material recycling", "recycle process"],
    category: "world",
    definition: "the collection and processing of discarded material into usable material",
    purpose: "reduce demand for some virgin resources and divert suitable waste from disposal",
    mechanism: "materials are collected, sorted, cleaned, transformed, and returned to manufacturing",
    importance: "effective recycling can reduce resource extraction and waste, though it also requires energy and suitable markets",
    example: "melting sorted aluminum cans to make new aluminum products",
    components: ["collection", "sorting", "processing", "manufacturing"],
    related: ["waste", "reuse", "materials", "sustainability"],
  },
  {
    id: "renewable-energy",
    term: "renewable energy",
    aliases: ["renewable power", "clean energy"],
    category: "world",
    definition: "energy obtained from sources replenished naturally on human timescales",
    purpose: "provide usable power without consuming a finite fuel stock",
    mechanism: "technology converts recurring flows such as sunlight, wind, water, or geothermal heat",
    importance: "renewable systems can reduce fuel depletion and greenhouse-gas emissions, with impacts depending on design",
    example: "solar panels converting sunlight into electricity",
    components: ["energy source", "conversion system", "storage or grid connection"],
    related: ["energy", "solar power", "wind power", "electricity"],
  },
  {
    id: "ocean",
    term: "an ocean",
    aliases: ["ocean", "oceans", "the sea"],
    category: "world",
    definition: "a vast connected body of salt water covering most of Earth's surface",
    purpose: "store and move water, heat, carbon, nutrients, and living organisms",
    mechanism: "winds, density differences, tides, and Earth's rotation drive circulation",
    importance: "oceans regulate climate, support biodiversity, supply food, and connect regions",
    example: "a current transporting warm water and heat across an ocean basin",
    components: ["water column", "seafloor", "currents", "coastal zones"],
    related: ["climate", "water cycle", "marine life", "continents"],
  },
  {
    id: "continent",
    term: "a continent",
    aliases: ["continent", "continents", "continental landmass"],
    category: "world",
    definition: "one of Earth's major continuous land divisions, defined by geographic and historical conventions",
    purpose: "organize large-scale descriptions of Earth's land and regions",
    mechanism: "continental crust forms large landmasses that move slowly through plate tectonics",
    importance: "continents provide a common geographic frame, although their boundaries and count are partly conventional",
    example: "Africa as a major connected landmass conventionally treated as a continent",
    components: ["continental crust", "regions", "boundaries"],
    related: ["geography", "countries", "oceans", "plate tectonics"],
  },
  {
    id: "country",
    term: "a country",
    aliases: ["country", "countries", "sovereign state"],
    category: "world",
    definition: "a political and geographic territory associated with a state, population, and governing institutions",
    purpose: "organize public authority and collective identity within recognized boundaries",
    mechanism: "institutions administer territory, law, public services, and external relations",
    importance: "countries are major units of government, law, citizenship, and international relations",
    example: "a state issuing laws and passports within its recognized territory",
    components: ["territory", "population", "government", "external relations"],
    related: ["government", "borders", "citizenship", "geography"],
  },
  {
    id: "map",
    term: "a map",
    aliases: ["map", "maps", "geographic map"],
    category: "world",
    definition: "a selective visual representation of spatial relationships",
    purpose: "show location, distance, direction, distribution, or movement",
    mechanism: "real-world features are transformed through scale, projection, symbols, and classification",
    importance: "maps make spatial patterns easier to compare, while every map also reflects design choices",
    example: "a transit map emphasizing routes and connections rather than exact ground distance",
    components: ["scale", "symbols", "projection", "legend", "extent"],
    related: ["geography", "location", "navigation", "data"],
  },
  {
    id: "earth",
    term: "Earth",
    aliases: ["earth", "planet earth", "our planet"],
    category: "world",
    definition: "the third planet from the Sun and the only known world with life",
    purpose: "serve as the physical planetary system containing human societies and known ecosystems",
    mechanism: "gravity binds its layered interior, surface, oceans, atmosphere, and orbiting Moon into a changing system",
    importance: "Earth supplies the conditions and materials on which all known life depends",
    example: "the coupled atmosphere, oceans, land, and biosphere exchanging energy and matter",
    components: ["core", "mantle", "crust", "oceans", "atmosphere"],
    related: ["solar system", "Moon", "climate", "life"],
  },
  {
    id: "solar-system",
    term: "the Solar System",
    aliases: ["solar system", "our solar system"],
    category: "world",
    definition: "the Sun and the objects gravitationally bound to it",
    purpose: "name the local planetary system containing Earth",
    mechanism: "the Sun's gravity governs the main orbital motion of planets, dwarf planets, asteroids, and comets",
    importance: "the Solar System is the immediate astronomical environment in which Earth formed and evolves",
    example: "Earth orbiting the Sun while the Moon orbits Earth",
    components: ["Sun", "planets", "dwarf planets", "small bodies"],
    related: ["astronomy", "Sun", "Earth", "orbits"],
  },
];
