import type { KnowledgeTopic } from "../types";

export const languageHumanitiesTopics: KnowledgeTopic[] = [
  {
    id: "language",
    term: "language",
    aliases: ["human language", "linguistic language"],
    category: "language",
    definition: "a structured system of signs and conventions used to express and interpret meaning",
    purpose: "communicate ideas, experiences, relationships, and intentions",
    mechanism: "communities connect sounds, marks, or gestures with grammatical patterns and shared meanings",
    importance: "language supports cooperation, memory, education, culture, and abstract thought",
    example: "English speakers combining words into a question",
    components: ["sounds or signs", "words", "grammar", "meaning", "use"],
    related: ["linguistics", "communication", "grammar", "context"],
  },
  {
    id: "linguistics",
    term: "linguistics",
    aliases: ["language science", "the study of language"],
    category: "language",
    definition: "the systematic study of language structure, meaning, use, variation, and change",
    purpose: "describe and explain how languages are organized and used",
    mechanism: "language evidence is analyzed across sounds, words, sentences, meanings, and social contexts",
    importance: "linguistics separates observable language patterns from prescriptive assumptions",
    example: "comparing how different sentence orders mark the subject of a clause",
    components: ["phonetics", "morphology", "syntax", "semantics", "pragmatics"],
    related: ["language", "grammar", "meaning", "communication"],
  },
  {
    id: "word",
    term: "a word",
    aliases: ["word", "words", "lexical item"],
    category: "language",
    definition: "a conventional language unit that can carry meaning or grammatical function",
    purpose: "name, describe, relate, or organize parts of a message",
    mechanism: "a recognized form connects pronunciation or spelling with possible meanings and uses",
    importance: "words provide reusable units from which larger expressions are built",
    example: "tree functioning as a noun in the sentence “The tree grew”",
    components: ["form", "meaning", "grammatical behavior"],
    related: ["morphemes", "sentences", "vocabulary", "context"],
  },
  {
    id: "sentence",
    term: "a sentence",
    aliases: ["sentence", "sentences", "complete sentence"],
    category: "language",
    definition: "a grammatically organized expression presented as a complete unit",
    purpose: "state, ask, request, or exclaim a complete message",
    mechanism: "words and phrases occupy grammatical roles and are interpreted together in context",
    importance: "sentences connect vocabulary with complete communicative acts",
    example: "“The train arrived early.”",
    components: ["one or more clauses", "grammatical structure", "intonation or punctuation"],
    related: ["clauses", "grammar", "syntax", "meaning"],
  },
  {
    id: "grammar",
    term: "grammar",
    aliases: ["language grammar", "grammatical system"],
    category: "language",
    definition: "the system of patterns that governs how language units combine and change form",
    purpose: "make relationships among parts of a message interpretable",
    mechanism: "word forms, order, agreement, and constructions signal grammatical roles",
    importance: "grammar lets speakers create and understand new expressions beyond memorized phrases",
    example: "English word order distinguishing “The dog chased the cat” from its reverse",
    components: ["morphology", "syntax", "constructions", "agreement"],
    related: ["syntax", "words", "sentences", "language"],
  },
  {
    id: "noun",
    term: "a noun",
    aliases: ["noun", "nouns", "naming word"],
    category: "language",
    definition: "a word class commonly used for people, places, things, substances, or abstract concepts",
    purpose: "introduce entities that can take roles in a clause",
    mechanism: "nouns head noun phrases and often vary for number or possession",
    importance: "nouns give language stable reference points for participants and concepts",
    example: "river in “The river widened”",
    components: ["common nouns", "proper nouns", "count nouns", "mass nouns"],
    related: ["pronouns", "noun phrases", "subjects", "objects"],
  },
  {
    id: "verb",
    term: "a verb",
    aliases: ["verb", "verbs", "action word"],
    category: "language",
    definition: "a word class that typically expresses an action, event, process, or state",
    purpose: "organize what happens or holds within a clause",
    mechanism: "verbs combine with participants and may mark tense, aspect, mood, or agreement",
    importance: "verbs usually form the structural center of a clause",
    example: "changes in “The weather changes quickly”",
    components: ["lexical verbs", "auxiliary verbs", "finite forms", "nonfinite forms"],
    related: ["predicates", "clauses", "tense", "subjects"],
  },
  {
    id: "adjective",
    term: "an adjective",
    aliases: ["adjective", "adjectives", "describing word"],
    category: "language",
    definition: "a word class that commonly describes a property of a noun or pronoun",
    purpose: "add information about qualities, categories, or states",
    mechanism: "adjectives modify nouns or appear after linking verbs",
    importance: "adjectives let speakers distinguish and evaluate entities more precisely",
    example: "quiet in “a quiet room”",
    components: ["attributive uses", "predicative uses", "comparative forms"],
    related: ["nouns", "adverbs", "modifiers", "description"],
  },
  {
    id: "adverb",
    term: "an adverb",
    aliases: ["adverb", "adverbs", "adverbial word"],
    category: "language",
    definition: "a word class that can modify a verb, adjective, another adverb, or a whole clause",
    purpose: "express circumstances such as manner, time, degree, frequency, or viewpoint",
    mechanism: "adverbs attach to the expression whose interpretation they narrow or qualify",
    importance: "adverbs make relations and circumstances more precise",
    example: "carefully in “She checked the result carefully”",
    components: ["manner", "time", "frequency", "degree"],
    related: ["verbs", "adjectives", "modifiers", "clauses"],
  },
  {
    id: "pronoun",
    term: "a pronoun",
    aliases: ["pronoun", "pronouns", "substitute noun"],
    category: "language",
    definition: "a grammatical word that can stand for or point to participants and entities",
    purpose: "refer without repeating a full noun phrase",
    mechanism: "its interpretation is recovered from context, discourse, or the speaking situation",
    importance: "pronouns make connected discourse shorter and help track participants",
    example: "she referring to a previously mentioned person",
    components: ["personal", "demonstrative", "relative", "interrogative pronouns"],
    related: ["nouns", "reference", "context", "agreement"],
  },
  {
    id: "preposition",
    term: "a preposition",
    aliases: ["preposition", "prepositions", "relational word"],
    category: "language",
    definition: "a grammatical word that introduces a phrase expressing a relation",
    purpose: "connect an entity with a place, time, direction, cause, method, or other relation",
    mechanism: "the preposition combines with a complement to form a prepositional phrase",
    importance: "prepositions express many compact relationships inside clauses",
    example: "under in “The key is under the book”",
    components: ["preposition", "complement", "prepositional phrase"],
    related: ["phrases", "nouns", "location", "grammar"],
  },
  {
    id: "clause",
    term: "a clause",
    aliases: ["clause", "clauses", "grammatical clause"],
    category: "language",
    definition: "a grammatical unit organized around a predicate and its participants",
    purpose: "express a situation that can form or contribute to a sentence",
    mechanism: "a predicate connects with subjects, objects, complements, or modifiers",
    importance: "clauses are the main building blocks for simple and complex sentences",
    example: "“when the rain stopped” inside a larger sentence",
    components: ["predicate", "arguments", "modifiers"],
    related: ["sentences", "verbs", "subjects", "syntax"],
  },
  {
    id: "paragraph",
    term: "a paragraph",
    aliases: ["paragraph", "paragraphs", "text paragraph"],
    category: "language",
    definition: "a group of connected sentences developed as one unit of text",
    purpose: "organize a main point and its supporting information",
    mechanism: "sentences are ordered through reference, transitions, and a shared topic",
    importance: "paragraphs divide longer writing into coherent units readers can follow",
    example: "a topic sentence followed by evidence and an explanation",
    components: ["main idea", "supporting sentences", "connections"],
    related: ["sentences", "coherence", "writing", "discourse"],
  },
  {
    id: "context",
    term: "context",
    aliases: ["linguistic context", "surrounding context"],
    category: "language",
    definition: "the surrounding language, situation, and shared knowledge that constrain interpretation",
    purpose: "select among possible meanings and recover unstated relationships",
    mechanism: "nearby words, discourse history, speaker goals, and circumstances supply interpretive evidence",
    importance: "the same form can mean different things under different conditions",
    example: "bank referring to land beside a river rather than a financial institution",
    components: ["co-text", "situation", "participants", "purpose"],
    related: ["meaning", "pragmatics", "discourse", "ambiguity"],
  },
  {
    id: "synonym",
    term: "a synonym",
    aliases: ["synonym", "synonyms", "similar word"],
    category: "language",
    definition: "a word or expression with a meaning similar to another in at least one context",
    purpose: "offer an alternative expression while preserving part of the intended meaning",
    mechanism: "two forms overlap semantically but may differ in tone, usage, or grammatical behavior",
    importance: "synonyms expand expression but must be chosen with context in mind",
    example: "begin and start in many ordinary sentences",
    components: ["source expression", "related expression", "shared sense", "usage limits"],
    related: ["antonyms", "vocabulary", "meaning", "thesaurus"],
  },
  {
    id: "antonym",
    term: "an antonym",
    aliases: ["antonym", "antonyms", "opposite word"],
    category: "language",
    definition: "a word or expression contrasted with another along a relevant meaning dimension",
    purpose: "express opposition or the other end of a semantic relation",
    mechanism: "language communities conventionally pair meanings as gradable, complementary, or relational opposites",
    importance: "antonyms clarify contrast and organize parts of vocabulary",
    example: "hot and cold as gradable opposites",
    components: ["gradable opposites", "complementaries", "relational opposites"],
    related: ["synonyms", "contrast", "meaning", "vocabulary"],
  },
  {
    id: "metaphor",
    term: "a metaphor",
    aliases: ["metaphor", "metaphors", "figurative comparison"],
    category: "language",
    definition: "an expression that understands or describes one domain in terms of another",
    purpose: "highlight selected similarities and create a compact conceptual image",
    mechanism: "features from a source concept are mapped onto a target concept without a literal identity claim",
    importance: "metaphor supports explanation, persuasion, creativity, and everyday abstract thought",
    example: "calling time a river to emphasize continuous movement",
    components: ["source domain", "target domain", "mapped relation"],
    related: ["figurative language", "analogy", "meaning", "literature"],
  },
  {
    id: "communication",
    term: "communication",
    aliases: ["human communication", "communicating"],
    category: "language",
    definition: "the process of creating, sending, receiving, and interpreting signals or messages",
    purpose: "coordinate understanding, action, relationships, and information",
    mechanism: "a sender encodes a message through a channel that a receiver interprets within context",
    importance: "communication enables cooperation but can fail when assumptions, signals, or contexts differ",
    example: "giving a colleague clear instructions and checking their interpretation",
    components: ["participants", "message", "channel", "context", "feedback"],
    related: ["language", "information", "listening", "context"],
  },
  {
    id: "history",
    term: "history",
    aliases: ["historical study", "the study of the past"],
    category: "humanities",
    definition: "the disciplined study and interpretation of past people, events, societies, and change",
    purpose: "reconstruct and explain the past from surviving evidence",
    mechanism: "sources are compared for origin, perspective, context, and consistency",
    importance: "history shows how present institutions and conditions developed",
    example: "comparing letters, laws, and material evidence to study a past movement",
    components: ["sources", "chronology", "context", "interpretation"],
    related: ["archives", "culture", "society", "evidence"],
  },
  {
    id: "geography",
    term: "geography",
    aliases: ["geographical study", "the study of places"],
    category: "humanities",
    definition: "the study of places, environments, spatial patterns, and relationships between people and Earth",
    purpose: "explain where things are, why they are there, and how places connect",
    mechanism: "maps, field observations, measurements, and spatial models reveal distributions and movement",
    importance: "geography links physical environments with population, culture, resources, and planning",
    example: "mapping how a river influences settlement locations",
    components: ["physical geography", "human geography", "mapping", "spatial analysis"],
    related: ["maps", "Earth", "environment", "society"],
  },
  {
    id: "culture",
    term: "culture",
    aliases: ["human culture", "cultural system"],
    category: "humanities",
    definition: "shared and learned patterns of meaning, practice, knowledge, and expression within a group",
    purpose: "organize identity, behavior, values, and communication",
    mechanism: "people learn and revise conventions through participation, teaching, imitation, and institutions",
    importance: "culture shapes interpretation while varying within every group and changing over time",
    example: "shared greeting customs learned within a community",
    components: ["practices", "values", "symbols", "knowledge", "institutions"],
    related: ["society", "language", "identity", "history"],
  },
  {
    id: "philosophy",
    term: "philosophy",
    aliases: ["philosophical inquiry", "the study of fundamental questions"],
    category: "humanities",
    definition: "the disciplined examination of fundamental questions about knowledge, reality, value, reason, and action",
    purpose: "clarify concepts, assumptions, arguments, and implications",
    mechanism: "claims are defined, reasons are tested, objections are considered, and distinctions are refined",
    importance: "philosophy improves reasoning about questions whose assumptions are often hidden",
    example: "examining what counts as knowledge rather than assuming a definition",
    components: ["logic", "epistemology", "ethics", "metaphysics", "aesthetics"],
    related: ["reasoning", "ethics", "knowledge", "logic"],
  },
  {
    id: "psychology",
    term: "psychology",
    aliases: ["psychological science", "the study of mind and behavior"],
    category: "humanities",
    definition: "the scientific study of behavior and mental processes",
    purpose: "describe, explain, and sometimes predict patterns in thought, emotion, and action",
    mechanism: "observations, experiments, surveys, and models connect behavior with biological and environmental factors",
    importance: "psychology informs learning, health, work, relationships, and human-centered design",
    example: "testing how spaced practice affects later memory",
    components: ["cognition", "development", "social behavior", "clinical study"],
    related: ["behavior", "mind", "learning", "neuroscience"],
  },
  {
    id: "sociology",
    term: "sociology",
    aliases: ["social science", "the study of society"],
    category: "humanities",
    definition: "the systematic study of society, social relationships, institutions, and group patterns",
    purpose: "explain how social structures and interactions influence people and change",
    mechanism: "research compares observations across groups, institutions, networks, and historical settings",
    importance: "sociology makes large-scale social patterns visible beyond individual experience",
    example: "studying how neighborhood resources relate to educational opportunity",
    components: ["institutions", "groups", "networks", "inequality", "change"],
    related: ["society", "culture", "economics", "history"],
  },
  {
    id: "economics",
    term: "economics",
    aliases: ["economic science", "the study of economies"],
    category: "humanities",
    definition: "the study of how people and institutions allocate scarce resources",
    purpose: "explain choices, exchange, production, distribution, and incentives",
    mechanism: "models connect constraints and incentives with observed behavior and outcomes",
    importance: "economics helps analyze tradeoffs in households, organizations, markets, and public policy",
    example: "studying how a price change affects demand for a product",
    components: ["microeconomics", "macroeconomics", "markets", "institutions"],
    related: ["resources", "markets", "money", "policy"],
  },
  {
    id: "government",
    term: "government",
    aliases: ["a government", "public government"],
    category: "humanities",
    definition: "the institutions and processes through which a political community makes and enforces collective decisions",
    purpose: "provide public rules, services, administration, representation, and security",
    mechanism: "authorized bodies create policy, collect resources, administer programs, and resolve disputes",
    importance: "government decisions shape rights, obligations, infrastructure, and shared resources",
    example: "a legislature passing a law that an executive agency administers",
    components: ["law-making", "administration", "courts", "public institutions"],
    related: ["law", "politics", "democracy", "society"],
  },
  {
    id: "democracy",
    term: "democracy",
    aliases: ["democratic government", "democratic system"],
    category: "humanities",
    definition: "a system of collective government in which political authority ultimately depends on the people",
    purpose: "make public power accountable through participation, representation, and protected procedures",
    mechanism: "rules distribute authority through elections, institutions, rights, and checks on power",
    importance: "democracy creates peaceful mechanisms for consent, disagreement, and leadership change",
    example: "citizens choosing representatives in a competitive election under established law",
    components: ["participation", "representation", "rights", "accountability"],
    related: ["government", "elections", "law", "citizenship"],
  },
  {
    id: "law",
    term: "law",
    aliases: ["the law", "legal rules"],
    category: "humanities",
    definition: "a system of publicly recognized rules and procedures enforced by institutions",
    purpose: "coordinate conduct, define rights and duties, and resolve disputes",
    mechanism: "authorized institutions create, interpret, and apply rules to cases",
    importance: "law provides structured expectations and limits on private and public action",
    example: "a court applying a statute to resolve a contract dispute",
    components: ["rules", "rights", "procedures", "institutions"],
    related: ["government", "courts", "justice", "rights"],
  },
  {
    id: "education",
    term: "education",
    aliases: ["learning system", "formal education"],
    category: "humanities",
    definition: "the organized process of developing knowledge, skills, judgment, and habits",
    purpose: "support learning and prepare people to participate in work, culture, and civic life",
    mechanism: "instruction, practice, feedback, reflection, and assessment reinforce understanding",
    importance: "education expands individual capability and preserves or revises shared knowledge",
    example: "a learner practicing a skill and using feedback to correct errors",
    components: ["instruction", "practice", "feedback", "assessment"],
    related: ["learning", "knowledge", "teaching", "skills"],
  },
  {
    id: "art",
    term: "art",
    aliases: ["the arts", "artistic expression"],
    category: "humanities",
    definition: "the creation and interpretation of expressive forms shaped by skill, imagination, and cultural context",
    purpose: "explore experience, communicate perspectives, and create aesthetic or conceptual effects",
    mechanism: "artists select media, forms, techniques, and conventions to organize an audience's attention",
    importance: "art preserves experience, challenges assumptions, and expands ways of perceiving",
    example: "a painting using color and composition to create a particular mood",
    components: ["medium", "form", "technique", "interpretation"],
    related: ["culture", "design", "music", "literature"],
  },
  {
    id: "music",
    term: "music",
    aliases: ["musical art", "organized sound"],
    category: "humanities",
    definition: "the organized use of sound and silence as an expressive art",
    purpose: "create patterns, emotion, movement, identity, or shared experience",
    mechanism: "rhythm, pitch, timbre, dynamics, and form shape expectation and perception",
    importance: "music supports expression, ritual, memory, entertainment, and social connection",
    example: "a melody developed over a repeating rhythmic pattern",
    components: ["rhythm", "melody", "harmony", "timbre", "form"],
    related: ["sound", "art", "culture", "performance"],
  },
  {
    id: "literature",
    term: "literature",
    aliases: ["literary writing", "written art"],
    category: "humanities",
    definition: "written or oral works valued for imaginative, expressive, or interpretive use of language",
    purpose: "represent experience, explore ideas, and create structured aesthetic effects",
    mechanism: "narrative, voice, imagery, rhythm, genre, and figurative language guide interpretation",
    importance: "literature preserves perspectives and lets readers examine lives and possibilities beyond their own",
    example: "a short story using a narrator to reveal a conflict gradually",
    components: ["language", "form", "genre", "voice", "theme"],
    related: ["language", "storytelling", "culture", "art"],
  },
];
