import type { KnowledgeTopic } from "../types";

export const lexiTopics: KnowledgeTopic[] = [
  {
    id: "lexi",
    term: "Lexi",
    aliases: ["lexi language", "the lexi model"],
    category: "lexi",
    definition: "Alphaine's deterministic mechanical language-model prototype",
    purpose: "interpret supported English structures and return traceable answers without generative token prediction",
    mechanism: "bounded phrase, knowledge, discourse, dictionary, context, connection, and structure modules process each request in order",
    importance: "it explores how inspectable linguistic rules and authored knowledge can produce useful language behavior",
    example: "matching a question about mathematics directly to an embedded semantic record",
    components: ["Extended Pack", "Discourse", "Search", "Context", "Connect", "Structure"],
    related: ["Alphaine", "linguistics", "deterministic models", "context"],
  },
  {
    id: "alphaine",
    term: "Alphaine",
    aliases: ["the alphaine project", "alphaine project"],
    category: "lexi",
    definition: "the project developing zero-generative-AI mechanical language models such as Lexi",
    purpose: "investigate language systems built from explicit linguistic mechanisms and inspectable sources",
    mechanism: "separate modules represent language analysis, knowledge connection, context selection, and sentence realization",
    importance: "the project tests an alternative to opaque statistical generation for bounded language tasks",
    example: "developing Lexi as a modular deterministic English-language prototype",
    components: ["mechanical models", "linguistic rules", "authored sources", "public traces"],
    related: ["Lexi", "linguistics", "determinism", "traceability"],
  },
  {
    id: "deterministic-model",
    term: "a deterministic language model",
    aliases: ["deterministic model", "mechanical language model", "rule-based language model"],
    category: "lexi",
    definition: "a language system whose output follows explicit data and rules rather than random or probabilistic generation",
    purpose: "produce repeatable, inspectable behavior for supported inputs",
    mechanism: "the same normalized input and source state pass through the same ordered decisions",
    importance: "determinism makes behavior reproducible and easier to audit",
    example: "returning the same reviewed definition every time the same supported question is asked",
    components: ["rules", "knowledge records", "routing", "structures", "fallbacks"],
    related: ["Lexi", "algorithms", "traceability", "linguistics"],
  },
  {
    id: "extended-pack",
    term: "the Extended Pack",
    aliases: ["extended pack", "extended phrase pack", "knowledge pack"],
    category: "lexi",
    definition: "Lexi's built-in collection of semantic records, question frames, conversation rules, and answer structures",
    purpose: "answer broad common questions directly without searching example sentences or opening the dictionary",
    mechanism: "a grammatical request frame identifies a focus and subject, then selects the corresponding authored field",
    importance: "it gives Lexi broader natural coverage while preserving explicit sources and deterministic behavior",
    example: "using a subject's purpose field to answer “What is it used for?”",
    components: ["knowledge topics", "aliases", "question frames", "conversation rules"],
    related: ["Lexi", "grammar", "knowledge", "answer structures"],
  },
  {
    id: "discourse-module",
    term: "the Discourse Module",
    aliases: ["discourse module", "connection structure module", "multi-part module"],
    category: "lexi",
    definition: "Lexi's component for separating and recombining bounded parts of a request",
    purpose: "handle multiple explicit questions and shared request frames in one message",
    mechanism: "sentence boundaries and recognized coordinators create up to four clauses that are answered independently and combined",
    importance: "it prevents two connected requests from collapsing into one unclear context",
    example: "turning “What is math and science?” into two definition requests",
    components: ["segmentation", "frame inheritance", "clause routing", "combination"],
    related: ["clauses", "context", "Structure Module", "coordination"],
  },
  {
    id: "search-module",
    term: "the Search Module",
    aliases: ["search module", "lexi search"],
    category: "lexi",
    definition: "Lexi's component for normalizing input and ranking recorded context entries",
    purpose: "retrieve the most relevant corpus evidence when direct packs do not answer",
    mechanism: "token overlap, phrase similarity, expanded terms, and sentence mode produce stable scores",
    importance: "search narrows a large corpus into inspectable candidates for context selection",
    example: "ranking examples about weather above unrelated examples for a weather question",
    components: ["normalization", "tokenization", "term expansion", "ranking"],
    related: ["Context Module", "examples", "similarity", "evidence"],
  },
  {
    id: "context-module",
    term: "the Context Module",
    aliases: ["context module", "lexi context"],
    category: "lexi",
    definition: "Lexi's component for selecting a supported intent from explicit rules and ranked evidence",
    purpose: "decide what kind of response a corpus-routed request supports",
    mechanism: "intent evidence is aggregated and checked against a confidence floor",
    importance: "weak evidence becomes an honest fallback instead of an invented answer",
    example: "selecting a weather intent only when its evidence is sufficiently strong",
    components: ["intent rules", "ranked matches", "confidence", "fallback"],
    related: ["Search Module", "context", "confidence", "Connect Module"],
  },
  {
    id: "connect-module",
    term: "the Connect Module",
    aliases: ["connect module", "lexi connect"],
    category: "lexi",
    definition: "Lexi's component for connecting a selected intent with bounded answer material",
    purpose: "prepare subject, action, object, qualifier, or recorded response slots",
    mechanism: "the selected intent retrieves compatible slots or a lexical record without writing the final sentence",
    importance: "connection keeps answer content separate from sentence formatting",
    example: "connecting a synonym request with a reviewed list of related words",
    components: ["intent", "source record", "answer slots", "lexical relations"],
    related: ["Context Module", "Structure Module", "slots", "knowledge"],
  },
  {
    id: "structure-module",
    term: "the Structure Module",
    aliases: ["structure module", "lexi structure", "sentence structure module"],
    category: "lexi",
    definition: "Lexi's component for placing bounded answer material into reviewed sentence forms",
    purpose: "produce readable grammatical output without free-form generation",
    mechanism: "an intent selects a literal structure whose declared slots are filled and cleaned",
    importance: "reviewed structures keep realization predictable and testable",
    example: "placing a subject and definition into a direct definition sentence",
    components: ["intent mapping", "templates", "slots", "surface cleanup"],
    related: ["grammar", "Connect Module", "sentences", "Discourse Module"],
  },
  {
    id: "dictionary-module",
    term: "the Dictionary Module",
    aliases: ["dictionary module", "lexi dictionary"],
    category: "lexi",
    definition: "Lexi's fallback component for retrieving definitions from the complete embedded Wordset archive",
    purpose: "define terms that are not authored in the Extended Pack",
    mechanism: "the compressed local archive is loaded once, cached, and searched by a normalized term",
    importance: "it expands lexical coverage while keeping the original dictionary record identifiable",
    example: "retrieving a Wordset definition and placing its source ID in the trace",
    components: ["request parser", "compressed archive", "cache", "lookup"],
    related: ["Wordset", "definitions", "Extended Pack", "traceability"],
  },
];
