import type { KnowledgeTopic } from "../types";

export const mathematicsComputingTopics: KnowledgeTopic[] = [
  {
    id: "mathematics",
    term: "mathematics",
    aliases: ["math", "maths"],
    category: "mathematics",
    definition: "the study of numbers, quantities, shapes, patterns, and logical relationships",
    purpose: "describe patterns, measure quantities, and solve problems precisely",
    mechanism: "definitions and assumptions are combined with logical steps to derive results",
    importance: "it provides a precise language for science, engineering, finance, and everyday reasoning",
    example: "using an equation to calculate distance from speed and time",
    components: ["arithmetic", "algebra", "geometry", "calculus", "statistics"],
    related: ["logic", "measurement", "science", "engineering"],
  },
  {
    id: "arithmetic",
    term: "arithmetic",
    aliases: ["basic math", "number operations"],
    category: "mathematics",
    definition: "the branch of mathematics concerned with numbers and basic operations",
    purpose: "add, subtract, multiply, divide, and compare quantities",
    mechanism: "number values are transformed according to fixed operational rules",
    importance: "it supports daily calculation and more advanced mathematics",
    example: "adding the prices of several items to find a total",
    components: ["addition", "subtraction", "multiplication", "division"],
    related: ["numbers", "fractions", "percentages", "algebra"],
  },
  {
    id: "algebra",
    term: "algebra",
    aliases: ["symbolic math", "symbolic mathematics"],
    category: "mathematics",
    definition: "a branch of mathematics that represents quantities and relationships with symbols",
    purpose: "describe general relationships and solve for unknown values",
    mechanism: "equivalent operations preserve an equation while an unknown is isolated",
    importance: "it turns repeated numerical problems into reusable general rules",
    example: "solving x + 4 = 9 to find that x equals 5",
    components: ["variables", "expressions", "equations", "functions"],
    related: ["arithmetic", "equations", "functions", "calculus"],
  },
  {
    id: "geometry",
    term: "geometry",
    aliases: ["shape mathematics", "spatial mathematics"],
    category: "mathematics",
    definition: "the branch of mathematics that studies shape, size, position, and space",
    purpose: "measure and reason about objects and spatial relationships",
    mechanism: "defined properties and theorems connect lengths, angles, areas, and volumes",
    importance: "it supports design, construction, mapping, art, and physical science",
    example: "calculating the area of a rectangular room",
    components: ["points", "lines", "angles", "shapes", "space"],
    related: ["measurement", "trigonometry", "architecture", "maps"],
  },
  {
    id: "calculus",
    term: "calculus",
    aliases: ["differential calculus", "integral calculus"],
    category: "mathematics",
    definition: "the mathematics of continuous change and accumulation",
    purpose: "measure rates of change and totals built from very small parts",
    mechanism: "limits define derivatives for change and integrals for accumulation",
    importance: "it models motion, growth, fields, optimization, and many physical systems",
    example: "finding the instantaneous speed of a moving object",
    components: ["limits", "derivatives", "integrals", "series"],
    related: ["functions", "algebra", "physics", "optimization"],
  },
  {
    id: "statistics",
    term: "statistics",
    aliases: ["statistical analysis", "stats"],
    category: "mathematics",
    definition: "the study of collecting, describing, and drawing conclusions from data",
    purpose: "summarize evidence and estimate patterns or uncertainty",
    mechanism: "data are sampled, measured, modeled, and compared with explicit assumptions",
    importance: "it helps distinguish supported patterns from impressions or random variation",
    example: "estimating an average from a survey while reporting its margin of error",
    components: ["data collection", "descriptive statistics", "inference", "modeling"],
    related: ["probability", "data", "experiments", "uncertainty"],
  },
  {
    id: "probability",
    term: "probability",
    aliases: ["chance", "likelihood"],
    category: "mathematics",
    definition: "a numerical description of how likely an event is",
    purpose: "reason consistently about uncertainty",
    mechanism: "possible outcomes and their conditions are represented on a scale from impossible to certain",
    importance: "it supports risk assessment, statistics, forecasting, and rational decisions",
    example: "describing a fair coin toss as having a one-half chance of heads",
    components: ["outcomes", "events", "conditions", "distributions"],
    related: ["statistics", "risk", "randomness", "prediction"],
  },
  {
    id: "fraction",
    term: "a fraction",
    aliases: ["fraction", "fractions", "fractional number"],
    category: "mathematics",
    definition: "a number that represents one quantity divided by another",
    purpose: "express parts, ratios, and non-whole quantities",
    mechanism: "a numerator names selected parts and a denominator names the equal-part scale",
    importance: "fractions connect division, ratios, decimals, and percentages",
    example: "three quarters representing three of four equal parts",
    components: ["numerator", "denominator", "fraction bar"],
    related: ["division", "ratio", "decimal", "percentage"],
  },
  {
    id: "percentage",
    term: "a percentage",
    aliases: ["percentage", "percent", "percentages"],
    category: "mathematics",
    definition: "a ratio expressed as a number of parts per hundred",
    purpose: "compare proportions on a common scale",
    mechanism: "a ratio is multiplied by one hundred and marked with the percent sign",
    importance: "percentages make changes, rates, discounts, and survey results easier to compare",
    example: "25 percent representing 25 out of every 100",
    components: ["part", "whole", "rate per hundred"],
    related: ["fraction", "decimal", "ratio", "proportion"],
  },
  {
    id: "equation",
    term: "an equation",
    aliases: ["equation", "equations", "mathematical equation"],
    category: "mathematics",
    definition: "a statement that two mathematical expressions have equal value",
    purpose: "represent a constraint or relationship that can be tested or solved",
    mechanism: "both sides remain equal when the same valid operation is applied to each",
    importance: "equations express relationships compactly and reveal unknown quantities",
    example: "2 + 3 = 5 or x + 3 = 5",
    components: ["left expression", "equals sign", "right expression"],
    related: ["algebra", "variables", "functions", "equality"],
  },
  {
    id: "algorithm",
    term: "an algorithm",
    aliases: ["algorithm", "algorithms", "procedure"],
    category: "computing",
    definition: "a finite, ordered set of instructions for completing a task or solving a class of problems",
    purpose: "turn a defined input into a repeatable output",
    mechanism: "each step applies an explicit operation, condition, or repetition rule",
    importance: "clear algorithms make behavior testable, reproducible, and suitable for automation",
    example: "sorting names by repeatedly comparing and moving them into order",
    components: ["inputs", "ordered steps", "conditions", "outputs"],
    related: ["logic", "programming", "data structures", "automation"],
  },
  {
    id: "computer",
    term: "a computer",
    aliases: ["computer", "computers", "computing machine"],
    category: "computing",
    definition: "an electronic machine that stores and processes data according to instructions",
    purpose: "perform calculations, transform information, and control digital processes",
    mechanism: "hardware executes encoded instructions while memory holds active data and programs",
    importance: "computers automate precise operations at scales and speeds difficult for manual work",
    example: "a laptop running a program that edits a document",
    components: ["processor", "memory", "storage", "input and output devices"],
    related: ["hardware", "software", "data", "programming"],
  },
  {
    id: "hardware",
    term: "computer hardware",
    aliases: ["hardware", "physical computer parts"],
    category: "computing",
    definition: "the physical components of a computer system",
    purpose: "store data, execute instructions, and exchange signals with people or other systems",
    mechanism: "electronic and mechanical components respond to electrical signals",
    importance: "software can operate only through physical processing, memory, storage, and communication devices",
    example: "a processor, keyboard, solid-state drive, or display",
    components: ["processor", "memory", "storage", "peripherals"],
    related: ["software", "computer", "electronics", "networks"],
  },
  {
    id: "software",
    term: "software",
    aliases: ["computer software", "programs", "application software"],
    category: "computing",
    definition: "encoded instructions and data that direct a computer's operations",
    purpose: "make hardware perform useful tasks",
    mechanism: "a processor interprets or executes program instructions within an operating environment",
    importance: "software makes general-purpose hardware adaptable to many different jobs",
    example: "a web browser displaying and interacting with a website",
    components: ["program code", "configuration", "data", "dependencies"],
    related: ["hardware", "programming", "operating systems", "applications"],
  },
  {
    id: "programming",
    term: "programming",
    aliases: ["coding", "computer programming", "software development"],
    category: "computing",
    definition: "the practice of designing and writing instructions that a computer can execute",
    purpose: "create reliable software and automated processes",
    mechanism: "requirements are represented as data, operations, conditions, and interfaces in a programming language",
    importance: "programming converts human procedures into repeatable machine behavior",
    example: "writing a function that calculates the total of a list of prices",
    components: ["problem definition", "code", "testing", "maintenance"],
    related: ["algorithms", "software", "logic", "debugging"],
  },
  {
    id: "data",
    term: "data",
    aliases: ["digital data", "information records"],
    category: "computing",
    definition: "recorded symbols, measurements, or observations that can be stored and processed",
    purpose: "represent facts or events in a form that can be examined",
    mechanism: "values are encoded according to a schema or convention and stored on a medium",
    importance: "reliable data provides evidence for calculation, communication, and decisions",
    example: "a table containing dates, product names, and sales quantities",
    components: ["values", "fields", "records", "metadata"],
    related: ["information", "databases", "statistics", "measurement"],
  },
  {
    id: "database",
    term: "a database",
    aliases: ["database", "databases", "data store"],
    category: "computing",
    definition: "an organized collection of data managed for efficient storage and retrieval",
    purpose: "preserve structured records and answer queries about them",
    mechanism: "a database system indexes, validates, reads, and updates records under defined rules",
    importance: "databases keep shared information consistent and searchable as it grows",
    example: "a product catalog with one record for each item",
    components: ["schema", "records", "indexes", "queries"],
    related: ["data", "tables", "queries", "software"],
  },
  {
    id: "internet",
    term: "the internet",
    aliases: ["internet", "global computer network"],
    category: "computing",
    definition: "a worldwide system of interconnected networks that exchange data using common protocols",
    purpose: "move digital information between connected devices and services",
    mechanism: "data is divided into packets, addressed, routed across networks, and reassembled",
    importance: "it enables global communication and access to distributed services",
    example: "a phone requesting a page from a server in another country",
    components: ["devices", "networks", "routers", "protocols"],
    related: ["web", "networks", "servers", "communication"],
  },
  {
    id: "world-wide-web",
    term: "the World Wide Web",
    aliases: ["web", "world wide web", "www"],
    category: "computing",
    definition: "a system of linked resources accessed over the internet",
    purpose: "publish, locate, and interact with documents and applications",
    mechanism: "browsers request identified resources from servers using web protocols",
    importance: "the web provides a common interface for sharing information and services",
    example: "opening a linked article in a browser",
    components: ["web pages", "links", "browsers", "servers"],
    related: ["internet", "websites", "URLs", "HTTP"],
  },
  {
    id: "website",
    term: "a website",
    aliases: ["website", "web site", "site"],
    category: "computing",
    definition: "a collection of related web pages and resources presented under a shared identity or address",
    purpose: "provide information or interactive services through a browser",
    mechanism: "a browser retrieves site resources and renders their structure, style, and behavior",
    importance: "websites make digital information and services broadly accessible",
    example: "an online reference with linked pages for different subjects",
    components: ["pages", "navigation", "content", "web assets"],
    related: ["web", "browser", "server", "URL"],
  },
  {
    id: "operating-system",
    term: "an operating system",
    aliases: ["operating system", "os", "system software"],
    category: "computing",
    definition: "system software that manages hardware and provides services to applications",
    purpose: "coordinate resources and give programs a stable environment",
    mechanism: "the kernel schedules work, controls memory and devices, and enforces access rules",
    importance: "it lets many programs share hardware safely and consistently",
    example: "macOS, Linux, Windows, Android, or iOS",
    components: ["kernel", "drivers", "file system", "system services"],
    related: ["hardware", "software", "applications", "files"],
  },
  {
    id: "network",
    term: "a computer network",
    aliases: ["network", "computer network", "digital network"],
    category: "computing",
    definition: "a group of devices connected so they can exchange data",
    purpose: "share information, resources, and services",
    mechanism: "interfaces send addressed signals through wired or wireless links under common protocols",
    importance: "networks allow separate machines to cooperate and communicate",
    example: "computers sharing a printer on the same local network",
    components: ["devices", "links", "addresses", "protocols"],
    related: ["internet", "routers", "servers", "communication"],
  },
  {
    id: "encryption",
    term: "encryption",
    aliases: ["data encryption", "cryptographic encryption"],
    category: "computing",
    definition: "the transformation of readable data into a form that requires a key to interpret",
    purpose: "protect information from unauthorized reading",
    mechanism: "a cryptographic algorithm combines data with a key to produce ciphertext",
    importance: "encryption supports privacy and secure communication over untrusted systems",
    example: "protecting a message while it travels between a browser and a server",
    components: ["plaintext", "algorithm", "key", "ciphertext"],
    related: ["security", "privacy", "cryptography", "authentication"],
  },
  {
    id: "artificial-intelligence",
    term: "artificial intelligence",
    aliases: ["ai", "machine intelligence"],
    category: "computing",
    definition: "a broad field concerned with machines performing tasks associated with perception, reasoning, learning, or decision-making",
    purpose: "automate or assist tasks that require structured interpretation or choice",
    mechanism: "different systems use different methods, including rules, search, optimization, and statistical learning",
    importance: "it can extend automation into complex tasks, but its evidence and limits must remain inspectable",
    example: "a rule system that classifies a known sentence form",
    components: ["representations", "algorithms", "inputs", "evaluation"],
    related: ["algorithms", "machine learning", "rules", "automation"],
  },
  {
    id: "machine-learning",
    term: "machine learning",
    aliases: ["ml", "statistical learning"],
    category: "computing",
    definition: "a family of methods that fit patterns or decision rules from data",
    purpose: "make predictions or classifications from observed examples",
    mechanism: "an optimization process adjusts model parameters to reduce an objective error on data",
    importance: "it can model patterns that are difficult to specify manually, although its results depend on data and evaluation",
    example: "classifying email as spam from measured features",
    components: ["training data", "model", "objective", "evaluation"],
    related: ["statistics", "artificial intelligence", "optimization", "data"],
  },
];
