import type { KnowledgeTopic } from "../types";

export const naturalScienceTopics: KnowledgeTopic[] = [
  {
    id: "science",
    term: "science",
    aliases: ["scientific study", "the sciences"],
    category: "science",
    definition: "a systematic way of studying the natural world through observation, measurement, explanation, and testing",
    purpose: "build explanations that can be checked against evidence",
    mechanism: "questions lead to observations or experiments whose results support, revise, or reject explanations",
    importance: "it provides a self-correcting method for distinguishing evidence from unsupported claims",
    example: "testing how light level affects the growth of otherwise similar plants",
    components: ["questions", "evidence", "hypotheses", "tests", "revision"],
    related: ["measurement", "experiments", "theories", "evidence"],
  },
  {
    id: "physics",
    term: "physics",
    aliases: ["physical science", "the study of matter and energy"],
    category: "science",
    definition: "the science of matter, energy, motion, forces, space, and time",
    purpose: "describe the fundamental behavior of physical systems",
    mechanism: "measurements are connected through mathematical models and tested predictions",
    importance: "physical principles underlie engineering, chemistry, astronomy, and modern technology",
    example: "using forces and mass to predict an object's acceleration",
    components: ["mechanics", "thermodynamics", "electromagnetism", "quantum physics"],
    related: ["mathematics", "energy", "force", "matter"],
  },
  {
    id: "chemistry",
    term: "chemistry",
    aliases: ["chemical science", "the study of substances"],
    category: "science",
    definition: "the science of substances, their structures, properties, and transformations",
    purpose: "explain and control how matter combines and changes",
    mechanism: "atomic arrangements and energy changes determine chemical bonds and reactions",
    importance: "chemistry connects microscopic structure to materials, medicine, food, and the environment",
    example: "observing acid and base reactions that produce new substances",
    components: ["atoms", "molecules", "bonds", "reactions"],
    related: ["physics", "biology", "matter", "energy"],
  },
  {
    id: "biology",
    term: "biology",
    aliases: ["life science", "the study of life"],
    category: "science",
    definition: "the science of living organisms and life processes",
    purpose: "explain how organisms are structured, function, reproduce, change, and interact",
    mechanism: "observations connect processes across molecules, cells, organisms, populations, and ecosystems",
    importance: "biology supports medicine, agriculture, conservation, and understanding of life",
    example: "studying how cells obtain and use energy",
    components: ["cell biology", "genetics", "evolution", "ecology"],
    related: ["cells", "organisms", "evolution", "ecosystems"],
  },
  {
    id: "astronomy",
    term: "astronomy",
    aliases: ["space science", "the study of space"],
    category: "science",
    definition: "the science of objects and events beyond Earth's atmosphere",
    purpose: "understand planets, stars, galaxies, and the universe",
    mechanism: "light and other signals are measured and compared with physical models",
    importance: "astronomy tests physics across vast scales and helps place Earth in a wider physical context",
    example: "using a star's spectrum to estimate its composition",
    components: ["planetary science", "stellar astronomy", "galaxies", "cosmology"],
    related: ["physics", "space", "stars", "planets"],
  },
  {
    id: "geology",
    term: "geology",
    aliases: ["earth science", "the study of rocks"],
    category: "science",
    definition: "the science of Earth's materials, structure, history, and physical processes",
    purpose: "explain how Earth changes and how its materials formed",
    mechanism: "rocks, landforms, fossils, and geophysical measurements preserve evidence of past and ongoing processes",
    importance: "geology informs resource use, hazard planning, climate history, and Earth's deep history",
    example: "reading layered rock to infer the order of past events",
    components: ["minerals", "rocks", "tectonics", "geologic time"],
    related: ["Earth", "rocks", "plate tectonics", "fossils"],
  },
  {
    id: "ecology",
    term: "ecology",
    aliases: ["ecological science", "environmental relationships"],
    category: "science",
    definition: "the study of relationships among organisms and their environments",
    purpose: "explain how living populations interact with resources and physical conditions",
    mechanism: "energy, materials, competition, cooperation, and environmental limits connect organisms within systems",
    importance: "ecology guides conservation and helps predict effects of environmental change",
    example: "studying how fewer pollinators affect plant reproduction",
    components: ["organisms", "populations", "communities", "ecosystems"],
    related: ["biology", "ecosystems", "biodiversity", "environment"],
  },
  {
    id: "matter",
    term: "matter",
    aliases: ["physical matter", "material substance"],
    category: "science",
    definition: "physical substance that has mass and occupies space",
    purpose: "form the material objects and systems studied in physical science",
    mechanism: "particles and fields combine into structures whose arrangement determines observable properties",
    importance: "matter is the material basis of ordinary objects, organisms, planets, and laboratory substances",
    example: "air, water, a stone, or a living cell",
    components: ["particles", "atoms", "molecules", "materials"],
    related: ["mass", "atoms", "energy", "chemistry"],
  },
  {
    id: "energy",
    term: "energy",
    aliases: ["physical energy", "capacity for work"],
    category: "science",
    definition: "a conserved physical quantity associated with the capacity to produce change",
    purpose: "describe transfers and transformations in physical systems",
    mechanism: "energy moves between objects or changes form while total energy is conserved in an isolated system",
    importance: "energy connects motion, heat, light, chemistry, electricity, and biological activity",
    example: "chemical energy in a battery becoming electrical energy and then light",
    components: ["kinetic energy", "potential energy", "thermal energy", "transfers"],
    related: ["work", "force", "heat", "electricity"],
  },
  {
    id: "force",
    term: "a force",
    aliases: ["force", "physical force", "push or pull"],
    category: "science",
    definition: "an interaction that can change an object's motion or shape",
    purpose: "describe how objects influence one another mechanically",
    mechanism: "a net force changes momentum and can cause acceleration",
    importance: "forces explain motion, balance, structures, machines, and many natural processes",
    example: "pushing a cart so that it accelerates",
    components: ["magnitude", "direction", "point of application"],
    related: ["motion", "mass", "acceleration", "energy"],
  },
  {
    id: "gravity",
    term: "gravity",
    aliases: ["gravitational force", "gravitation"],
    category: "science",
    definition: "the attraction associated with mass and the curvature of spacetime",
    purpose: "describe why masses influence motion toward one another",
    mechanism: "mass-energy shapes spacetime, and objects follow paths within that geometry",
    importance: "gravity organizes falling objects, orbits, planets, stars, and large-scale cosmic structure",
    example: "Earth keeping the Moon in orbit",
    components: ["mass", "distance", "gravitational field"],
    related: ["force", "mass", "orbits", "spacetime"],
  },
  {
    id: "atom",
    term: "an atom",
    aliases: ["atom", "atoms", "atomic particle"],
    category: "science",
    definition: "the smallest unit of an element that retains that element's chemical identity",
    purpose: "form the basic chemical units from which ordinary substances are built",
    mechanism: "electrons occupy regions around a nucleus containing protons and usually neutrons",
    importance: "atomic structure explains elements, bonding, reactions, and material properties",
    example: "a carbon atom with six protons",
    components: ["protons", "neutrons", "electrons"],
    related: ["elements", "molecules", "chemistry", "matter"],
  },
  {
    id: "molecule",
    term: "a molecule",
    aliases: ["molecule", "molecules", "molecular structure"],
    category: "science",
    definition: "a group of atoms held together in a defined arrangement",
    purpose: "form chemical substances with properties determined by their atoms and structure",
    mechanism: "atoms share or redistribute electrons to create chemical bonds",
    importance: "molecules connect atomic structure to the behavior of materials and living systems",
    example: "a water molecule containing two hydrogen atoms and one oxygen atom",
    components: ["atoms", "chemical bonds", "three-dimensional arrangement"],
    related: ["atoms", "compounds", "chemistry", "materials"],
  },
  {
    id: "cell",
    term: "a cell",
    aliases: ["biological cell", "cells", "unit of life"],
    category: "science",
    definition: "the smallest organized unit capable of carrying out the basic processes of life",
    purpose: "maintain living processes, store information, use energy, and reproduce",
    mechanism: "a membrane regulates exchanges while internal molecular systems perform specialized reactions",
    importance: "all known organisms consist of one or more cells",
    example: "a bacterium functioning as a single cell",
    components: ["cell membrane", "genetic material", "cytoplasm", "molecular machinery"],
    related: ["biology", "organisms", "DNA", "metabolism"],
  },
  {
    id: "dna",
    term: "DNA",
    aliases: ["dna", "deoxyribonucleic acid", "genetic material"],
    category: "science",
    definition: "a molecule that stores hereditary information in most living organisms",
    purpose: "encode instructions used in growth, function, reproduction, and inheritance",
    mechanism: "sequences of nucleotide bases are copied and read through cellular processes",
    importance: "DNA connects inherited information with biological structure and variation",
    example: "a gene represented by a particular sequence of DNA bases",
    components: ["nucleotides", "bases", "sugar-phosphate backbone", "double helix"],
    related: ["genes", "cells", "inheritance", "proteins"],
  },
  {
    id: "evolution",
    term: "evolution",
    aliases: ["biological evolution", "evolution by natural selection"],
    category: "science",
    definition: "change in inherited characteristics of populations across generations",
    purpose: "explain the diversity, adaptation, and shared history of living organisms",
    mechanism: "variation, inheritance, selection, mutation, and chance alter trait frequencies over time",
    importance: "evolution unifies evidence across genetics, fossils, anatomy, ecology, and biogeography",
    example: "a bacterial population becoming more resistant after repeated antibiotic exposure",
    components: ["variation", "inheritance", "selection", "time"],
    related: ["genetics", "natural selection", "species", "ecology"],
  },
  {
    id: "photosynthesis",
    term: "photosynthesis",
    aliases: ["plant photosynthesis", "light-powered sugar production"],
    category: "science",
    definition: "the process by which plants, algae, and some microbes use light to build energy-rich molecules",
    purpose: "store light energy in chemical form",
    mechanism: "light-driven reactions supply energy used to combine carbon dioxide and water into sugars",
    importance: "photosynthesis supplies much of the food and oxygen supporting Earth's ecosystems",
    example: "a green leaf producing sugars in sunlight",
    components: ["light capture", "electron transfer", "carbon fixation"],
    related: ["plants", "sunlight", "carbon dioxide", "oxygen"],
  },
  {
    id: "ecosystem",
    term: "an ecosystem",
    aliases: ["ecosystem", "ecosystems", "ecological system"],
    category: "science",
    definition: "a community of organisms interacting with one another and with their physical environment",
    purpose: "describe connected flows of energy and materials in a place",
    mechanism: "feeding, decomposition, competition, climate, water, and nutrients link living and nonliving parts",
    importance: "ecosystem function supports habitats, food production, water cycles, and nutrient renewal",
    example: "a pond containing water, microbes, plants, insects, fish, and surrounding soil",
    components: ["organisms", "environment", "energy flow", "material cycles"],
    related: ["ecology", "habitat", "food webs", "biodiversity"],
  },
  {
    id: "scientific-method",
    term: "the scientific method",
    aliases: ["scientific method", "scientific process", "experimental method"],
    category: "science",
    definition: "a family of disciplined practices for developing and testing explanations with evidence",
    purpose: "make claims inspectable, repeatable, and open to correction",
    mechanism: "a question is translated into a test, evidence is collected, and conclusions are compared with alternatives",
    importance: "it reduces reliance on authority, intuition, and selective observation",
    example: "changing one measured factor while holding other conditions as constant as practical",
    components: ["question", "hypothesis", "test", "analysis", "revision"],
    related: ["science", "experiments", "evidence", "measurement"],
  },
  {
    id: "hypothesis",
    term: "a hypothesis",
    aliases: ["hypothesis", "scientific hypothesis", "testable explanation"],
    category: "science",
    definition: "a proposed explanation or expectation that can be checked against evidence",
    purpose: "turn a question into a specific testable claim",
    mechanism: "the hypothesis implies observations that should differ depending on whether it is supported",
    importance: "a clear hypothesis makes reasoning and possible correction visible",
    example: "predicting that seedlings under more light will grow faster under otherwise similar conditions",
    components: ["claim", "conditions", "predicted observation"],
    related: ["experiments", "prediction", "evidence", "theory"],
  },
  {
    id: "theory-science",
    term: "a scientific theory",
    aliases: ["scientific theory", "theory in science"],
    category: "science",
    definition: "a broad, well-supported explanatory framework that connects many observations and tested hypotheses",
    purpose: "organize evidence and generate new testable predictions",
    mechanism: "multiple models and principles are checked repeatedly across independent lines of evidence",
    importance: "theories provide coherent explanations while remaining open to revision by better evidence",
    example: "evolutionary theory connecting inheritance, fossils, variation, and natural selection",
    components: ["principles", "evidence", "models", "predictions"],
    related: ["hypothesis", "evidence", "models", "science"],
  },
  {
    id: "experiment",
    term: "an experiment",
    aliases: ["experiment", "experiments", "controlled test"],
    category: "science",
    definition: "a structured test in which observations are made under defined conditions",
    purpose: "compare explanations or estimate the effect of a change",
    mechanism: "conditions are controlled or randomized so measured differences can be interpreted",
    importance: "experiments can provide stronger evidence about causes than observation alone",
    example: "comparing two groups that differ only in a deliberately assigned treatment",
    components: ["question", "variables", "conditions", "measurements"],
    related: ["scientific method", "hypotheses", "controls", "evidence"],
  },
  {
    id: "measurement",
    term: "measurement",
    aliases: ["measuring", "scientific measurement"],
    category: "science",
    definition: "the assignment of a value to a property according to a defined standard",
    purpose: "make observations comparable and precise",
    mechanism: "an instrument or procedure compares a property with a unit and records uncertainty",
    importance: "measurement connects claims to reproducible evidence",
    example: "recording length in meters with a calibrated ruler",
    components: ["property", "unit", "instrument", "uncertainty"],
    related: ["data", "units", "experiments", "accuracy"],
  },
  {
    id: "electricity",
    term: "electricity",
    aliases: ["electric power", "electrical energy"],
    category: "science",
    definition: "phenomena associated with electric charge, fields, current, and potential",
    purpose: "transfer energy and signals through controlled movement or arrangement of charge",
    mechanism: "voltage can drive electric current through a conductive path",
    importance: "electricity powers modern devices, communication, lighting, and infrastructure",
    example: "a battery driving current through a lamp circuit",
    components: ["charge", "voltage", "current", "circuit"],
    related: ["energy", "magnetism", "circuits", "electrons"],
  },
  {
    id: "light",
    term: "light",
    aliases: ["visible light", "electromagnetic light"],
    category: "science",
    definition: "electromagnetic radiation, with visible light being the portion human eyes can detect",
    purpose: "carry energy and information through space",
    mechanism: "electromagnetic fields propagate as waves and interact in discrete energy exchanges",
    importance: "light enables vision, photosynthesis, imaging, communication, and astronomical observation",
    example: "sunlight traveling to Earth and being reflected by an object into an eye",
    components: ["wavelength", "frequency", "energy", "polarization"],
    related: ["electromagnetism", "color", "photons", "vision"],
  },
];
