// Generated by build-dv12-indexes.mjs; SHA-256 pins the complete index tree.
export const DV12_CATALOG = {
  "path": "/dv12/catalog.json.gz",
  "sha256": "1ca0004a375aff5e2ed443dc7df8b8adb33d4318ce436b281a065624e73bfda5",
  "sizeBytes": 312472,
  "decodedSha256": "c476adf903726371c11bca1f5bf4f3f4cab152deeeafb3a11ddd8f563269f40e",
  "decodedSizeBytes": 1251038
} as const;
