// Generated by build-dv12-indexes.mjs; SHA-256 pins the complete index tree.
export const DV12_CATALOG = {
  "path": "/dv12/catalog.json.gz",
  "sha256": "c179c841883479af784e90ee1d0be9c5fd4066df6ab3eca5547c6c12464b043e",
  "sizeBytes": 385170,
  "decodedSha256": "885c33ae15fe4e21424c3dc34ec1a22cc622e0f4284cddc5ddaff3bd6e4cd061",
  "decodedSizeBytes": 1465993
} as const;
