// Generated by build-dv12-indexes.mjs; SHA-256 pins the complete index tree.
export const DV12_CATALOG = {
  "path": "/dv12/catalog.json.gz",
  "sha256": "ecd3c18a29f2d6b29f54cfbad9d9e50b65b1d2c130a4c4df401a937ecd6f698e",
  "sizeBytes": 380945,
  "decodedSha256": "6e9d76ca46add834a6cf1002d14f0a4c1c7ba4be6dc2fd7051e1b5440050ce8f",
  "decodedSizeBytes": 1449679
} as const;
