// Generated by build-dv15-data-packs.mjs.
export const DV15_CATALOG = {
  "path": "/dv15/catalog.json.gz",
  "sha256": "aacbecd4fbdbf97a80b4d55e6a389d4672e7195361a969d1c376a008931cde34",
  "sizeBytes": 120277,
  "decodedSha256": "4d6ca180a8be2cbcdacb1526cef0f415d5beaffd21aec1405ac1853885b7eaa9",
  "decodedSizeBytes": 482694
} as const;
